package com.thecompanyinc.cobblemoninitiative.npcmap;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.thecompanyinc.cobblemoninitiative.npcsight.NpcSightInit;
import com.thecompanyinc.cobblemoninitiative.npcsight.NpcSightManager;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.InputStreamReader;
import java.io.Reader;
import java.nio.charset.StandardCharsets;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.Map;
import java.util.Set;
import java.util.UUID;
import net.fabricmc.fabric.api.event.lifecycle.v1.ServerEntityEvents;
import net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents;
import net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents;
import net.fabricmc.loader.api.FabricLoader;
import net.minecraft.commands.CommandSourceStack;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.packs.resources.Resource;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.level.storage.LevelResource;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Applies shipped Easy NPC presets to placed in-world NPCs — per NPC, as its chunk loads.
 *
 * Why not one bulk import at install time: Easy NPC's {@code preset import} only updates an
 * NPC in place when its entity is currently loaded; for an unloaded UUID it would spawn a
 * duplicate at the preset position (or 0,0,0). A one-shot function run from spawn therefore
 * cannot reach a map's worth of NPCs. Instead this manager keeps a per-NPC "applied content
 * version" in the world save and re-imports each mapped NPC the first time it loads after
 * the shipped content changed (or after {@code install run} arms a full refresh).
 *
 * Inputs:
 * <ul>
 *   <li>{@code cobblemon_initiative:npc/preset_map.json} — bundled UUID→preset map with a
 *       content-hash version (covers the mapping AND the preset file bytes), generated by
 *       {@code scripts/generate_npc_function}.</li>
 *   <li>{@code data/npc_preset_refresh.json} in the world dir — per-NPC applied version and
 *       sticky preset overrides. An override (the Granary keeper's current trade tier)
 *       replaces the bundled preset location permanently until the next tier event, so a
 *       content-version refresh re-imports the CURRENT tier, never the base catalog.</li>
 * </ul>
 *
 * Import command shape (Easy NPC 6.25 grammar — a UUID is only accepted after a position):
 * {@code execute as <uuid> at @s run easy_npc preset import data <location> ~ ~ ~ <uuid>}
 */
public final class NpcPresetRefreshManager {

  private static final Logger LOGGER = LoggerFactory.getLogger("cobblemon-initiative-npcmap");

  private static final Gson GSON = new GsonBuilder().setPrettyPrinting().create();

  private static final ResourceLocation PRESET_MAP_RESOURCE =
    ResourceLocation.fromNamespaceAndPath("cobblemon_initiative", "npc/preset_map.json");

  private static final String STATE_FILE = "data/npc_preset_refresh.json";

  /** Easy NPC 6.25 DATA preset constraints (PresetSecurity). */
  private static final String PRESET_NAMESPACE = "easy_npc";
  private static final String PRESET_PREFIX = "preset/";
  private static final String PRESET_SUFFIX = ".npc.snbt";

  /** Max preset imports dispatched per server tick (each parses an SNBT file). */
  private static final int IMPORTS_PER_TICK = 4;

  // Bundled content (read from mod resources on server start)
  private static String contentVersion = "";
  private static final Map<UUID, String> bundledPresets = new LinkedHashMap<>();

  // Per-world state
  private static final Map<UUID, String> appliedVersion = new LinkedHashMap<>();
  private static final Map<UUID, String> presetOverride = new LinkedHashMap<>();
  private static File stateFile;
  private static boolean dirty;

  // Refresh queue. Entities are queued on ENTITY_LOAD and imported one tick later, so
  // Easy NPC's own entity registration (also an entity-load listener) has settled.
  private static final Set<UUID> incoming = new LinkedHashSet<>();
  private static final Set<UUID> ready = new LinkedHashSet<>();

  private static Boolean easyNpcPresent;

  private NpcPresetRefreshManager() {}

  /** True once the event listeners are registered — init() must be once-only. */
  private static boolean initialized;

  public static void init() {
    // Idempotent: a second call would double-register every listener (double imports).
    // Init moved to InitiativeInit 2026-07-11; the guard protects against any stray
    // legacy call sites reappearing.
    if (initialized) return;
    initialized = true;
    ServerLifecycleEvents.SERVER_STARTED.register(NpcPresetRefreshManager::load);
    ServerLifecycleEvents.SERVER_STOPPING.register(server -> save());
    ServerEntityEvents.ENTITY_LOAD.register(NpcPresetRefreshManager::onEntityLoad);
    ServerTickEvents.END_SERVER_TICK.register(NpcPresetRefreshManager::tick);
  }

  // ---------------------------------------------------------------------------
  // Lifecycle
  // ---------------------------------------------------------------------------

  private static void load(MinecraftServer server) {
    contentVersion = "";
    bundledPresets.clear();
    appliedVersion.clear();
    presetOverride.clear();
    incoming.clear();
    ready.clear();
    dirty = false;

    // Bundled UUID→preset map
    try {
      Resource resource =
        server.getResourceManager().getResource(PRESET_MAP_RESOURCE).orElse(null);
      if (resource == null) {
        LOGGER.warn("[NPC Refresh] Bundled preset map {} not found.", PRESET_MAP_RESOURCE);
      } else {
        try (Reader reader = new InputStreamReader(resource.open(), StandardCharsets.UTF_8)) {
          JsonObject root = GSON.fromJson(reader, JsonObject.class);
          contentVersion = root.has("version") ? root.get("version").getAsString() : "";
          JsonObject npcs = root.has("npcs") ? root.getAsJsonObject("npcs") : new JsonObject();
          for (Map.Entry<String, JsonElement> e : npcs.entrySet()) {
            try {
              UUID uuid = UUID.fromString(e.getKey());
              JsonElement value = e.getValue();
              String preset = value.isJsonObject()
                ? value.getAsJsonObject().get("preset").getAsString()
                : value.getAsString();
              bundledPresets.put(uuid, resolvePresetLocation(preset));
            } catch (Exception bad) {
              LOGGER.warn("[NPC Refresh] Skipping bad preset map entry {}: {}",
                e.getKey(), bad.getMessage());
            }
          }
        }
      }
    } catch (Exception e) {
      LOGGER.error("[NPC Refresh] Failed to read bundled preset map: {}", e.getMessage());
    }

    // Per-world applied/override state
    stateFile = server.getWorldPath(LevelResource.ROOT).resolve(STATE_FILE).toFile();
    if (stateFile.exists()) {
      try (FileReader reader = new FileReader(stateFile)) {
        JsonObject root = GSON.fromJson(reader, JsonObject.class);
        if (root != null) {
          if (root.has("applied")) {
            for (Map.Entry<String, JsonElement> e : root.getAsJsonObject("applied").entrySet()) {
              appliedVersion.put(UUID.fromString(e.getKey()), e.getValue().getAsString());
            }
          }
          if (root.has("overrides")) {
            for (Map.Entry<String, JsonElement> e : root.getAsJsonObject("overrides").entrySet()) {
              presetOverride.put(UUID.fromString(e.getKey()), e.getValue().getAsString());
            }
          }
        }
      } catch (Exception e) {
        LOGGER.error("[NPC Refresh] Error loading state: {}", e.getMessage());
      }
    }

    // Spawn-chunk NPCs load BEFORE SERVER_STARTED (so their ENTITY_LOAD fired while the
    // bundled map was still empty) — pick them up here; everything else queues on load.
    if (isEasyNpcPresent()) {
      Set<UUID> known = new LinkedHashSet<>(bundledPresets.keySet());
      known.addAll(presetOverride.keySet());
      for (UUID uuid : known) {
        if (needsRefresh(uuid) && findLoadedEntity(server, uuid) != null) {
          incoming.add(uuid);
        }
      }
    }

    LOGGER.info(
      "[NPC Refresh] Content version {} — {} mapped NPC(s), {} tier override(s), {} loaded now.",
      contentVersion.isEmpty() ? "(none)" : contentVersion,
      bundledPresets.size(),
      presetOverride.size(),
      incoming.size()
    );
  }

  private static void save() {
    if (stateFile == null || !dirty) return;
    try {
      stateFile.getParentFile().mkdirs();
      JsonObject root = new JsonObject();
      JsonObject applied = new JsonObject();
      appliedVersion.forEach((uuid, ver) -> applied.addProperty(uuid.toString(), ver));
      JsonObject overrides = new JsonObject();
      presetOverride.forEach((uuid, rl) -> overrides.addProperty(uuid.toString(), rl));
      root.add("applied", applied);
      root.add("overrides", overrides);
      try (FileWriter writer = new FileWriter(stateFile)) {
        GSON.toJson(root, writer);
      }
      dirty = false;
    } catch (Exception e) {
      // Exception, not IOException: Gson throws JsonIOException (a RuntimeException),
      // and save() is reached synchronously from `install run` — an escape here would
      // abort the command before the branded disconnect is scheduled.
      LOGGER.error("[NPC Refresh] Error saving state: {}", e.getMessage());
    }
  }

  // ---------------------------------------------------------------------------
  // Events
  // ---------------------------------------------------------------------------

  private static void onEntityLoad(Entity entity, ServerLevel level) {
    UUID uuid = entity.getUUID();
    if (!bundledPresets.containsKey(uuid) && !presetOverride.containsKey(uuid)) return;
    if (!isEasyNpcPresent()) return;
    if (needsRefresh(uuid)) {
      incoming.add(uuid);
    }
  }

  private static void tick(MinecraftServer server) {
    if (!ready.isEmpty()) {
      int budget = IMPORTS_PER_TICK;
      var it = ready.iterator();
      while (it.hasNext() && budget > 0) {
        UUID uuid = it.next();
        it.remove();
        budget--;
        applyNow(server, uuid);
      }
      if (ready.isEmpty()) save();
    }
    if (!incoming.isEmpty()) {
      ready.addAll(incoming);
      incoming.clear();
    }
  }

  // ---------------------------------------------------------------------------
  // Application
  // ---------------------------------------------------------------------------

  private static boolean needsRefresh(UUID uuid) {
    return !contentVersion.equals(appliedVersion.get(uuid));
  }

  private static void applyNow(MinecraftServer server, UUID uuid) {
    if (!needsRefresh(uuid)) return;
    Entity entity = findLoadedEntity(server, uuid);
    if (entity == null) return; // unloaded again — re-queued on its next load

    // A sticky override (the keeper's current trade tier) beats the bundled base preset,
    // so a content-version refresh re-imports the CURRENT tier, never the base catalog.
    String location = presetOverride.getOrDefault(uuid, bundledPresets.get(uuid));
    if (location == null) return;

    // A sight-manager follow must come off BEFORE the import replaces the objective set —
    // afterwards the live goal is orphaned (unremovable by command) and the NPC keeps
    // following until the entity reloads. An unfired approach re-acquires on a later tick.
    NpcSightManager sight = NpcSightInit.getManager();
    if (sight != null) sight.teardownPursuit(server, uuid);

    // performPrefixedCommand is void and swallows command errors (they only reach the
    // suppressed source) — the result callback is the ONE honest success signal. Only a
    // confirmed import is marked applied; failures stay pending and retry on next load.
    final boolean[] succeeded = {false};
    CommandSourceStack src = server
      .createCommandSourceStack()
      .withPermission(4)
      .withSuppressedOutput()
      .withCallback((success, result) -> {
        if (success) succeeded[0] = true;
      });
    try {
      server.getCommands().performPrefixedCommand(src, importCommand(uuid, location));
    } catch (Exception e) {
      LOGGER.warn("[NPC Refresh] Import threw for {}: {}", uuid, e.getMessage());
      return;
    }

    if (succeeded[0]) {
      appliedVersion.put(uuid, contentVersion);
      dirty = true;
      LOGGER.info("[NPC Refresh] Applied {} to {}", location, uuid);
      // No shipped preset carries a FOLLOW objective, so a follow goal that survived the
      // import is an orphan from the replaced objective set. The pre-import teardown covers
      // sight-manager follows; this purge is the backstop for everything else — e.g. the
      // tenants_of_record escort (datapack-issued follow, re-arms on a ~100-tick cadence).
      int purged = NpcSightManager.purgeFollowGoals(entity);
      if (purged > 0) {
        LOGGER.warn(
          "[NPC Refresh] Purged {} orphaned follow goal(s) on {} after import.", purged, uuid);
      }
    } else {
      LOGGER.warn(
        "[NPC Refresh] Import failed for {} ({}) — will retry on next chunk load.",
        uuid,
        location
      );
    }
  }

  private static Entity findLoadedEntity(MinecraftServer server, UUID uuid) {
    for (ServerLevel level : server.getAllLevels()) {
      Entity entity = level.getEntity(uuid);
      if (entity != null) return entity;
    }
    return null;
  }

  // ---------------------------------------------------------------------------
  // Public API
  // ---------------------------------------------------------------------------

  /** Result of {@link #armFullRefresh}: total mapped NPCs and how many were loaded right now. */
  public record ArmResult(int mapped, int loadedNow) {}

  /**
   * Forget all applied versions so every mapped NPC re-imports its preset the next time it
   * loads; NPCs that are loaded right now are queued immediately. Sticky tier overrides
   * survive, so the Granary keeper refreshes to its CURRENT tier. Called by `install run`.
   */
  public static ArmResult armFullRefresh(MinecraftServer server) {
    // Callers follow this with direct preset imports in the same tick (update_npc_presets /
    // the legacy npc-map loop) — drop live sight-manager follows first so those imports
    // don't orphan them. Follows those imports still orphan (datapack escorts, flag desyncs)
    // are healed by applyNow's post-import purge when the armed refresh re-imports the NPC.
    NpcSightManager sight = NpcSightInit.getManager();
    if (sight != null) sight.teardownAllPursuits(server);

    appliedVersion.clear();
    dirty = true;
    int loadedNow = 0;
    if (isEasyNpcPresent()) {
      Set<UUID> known = new LinkedHashSet<>(bundledPresets.keySet());
      known.addAll(presetOverride.keySet());
      for (UUID uuid : known) {
        if (findLoadedEntity(server, uuid) != null) {
          incoming.add(uuid);
          loadedNow++;
        }
      }
    }
    save();
    return new ArmResult(bundledPresets.size(), loadedNow);
  }

  /**
   * Record the Granary trade tier for every mapped granary_keeper NPC as a STICKY override
   * (it replaces the bundled base preset until the next tier event). Keepers loaded right
   * now retier within ticks (the granary/apply_<tier> function usually beats us to it —
   * re-importing the same preset is harmless); unloaded keepers get the tier preset the
   * next time their chunk loads instead of silently keeping stale trades.
   */
  public static void queueTierOverride(MinecraftServer server, String tier) {
    if (bundledPresets.isEmpty()) return;
    for (Map.Entry<UUID, String> e : bundledPresets.entrySet()) {
      String location = e.getValue();
      String basename = location.substring(location.lastIndexOf('/') + 1);
      if (!basename.startsWith("granary_keeper")) continue;
      String dir = location.substring(0, location.lastIndexOf('/') + 1);
      String override = dir + "granary_keeper_" + tier + PRESET_SUFFIX;
      presetOverride.put(e.getKey(), override);
      appliedVersion.remove(e.getKey()); // force re-apply even at an unchanged content version
      dirty = true;
      if (isEasyNpcPresent() && findLoadedEntity(server, e.getKey()) != null) {
        incoming.add(e.getKey());
      }
    }
    save();
  }

  /** True when the bundled preset map was found and is non-empty. */
  public static boolean hasBundledMap() {
    return !bundledPresets.isEmpty();
  }

  /**
   * The single valid Easy NPC 6.25 import-onto-existing-NPC command: grammar is
   * {@code preset import data <location> [<x y z> [<uuid>]]} — the UUID is only accepted
   * after a position, so the command runs as/at the NPC and passes ~ ~ ~. When the UUID is
   * not loaded the execute-as target resolves to nothing and the line is a safe no-op.
   */
  public static String importCommand(UUID uuid, String presetLocation) {
    return "execute as " + uuid + " at @s run easy_npc preset import data "
      + presetLocation + " ~ ~ ~ " + uuid;
  }

  /**
   * Expand a short preset name to the shipped Easy NPC DATA preset resource location
   * (mirror of resolve_preset in scripts/generate_npc_function):
   *
   * <pre>
   *   "cyber_leader"             → easy_npc:preset/humanoid/cyber_leader.npc.snbt
   *   "humanoid_slim/nalia_mom"  → easy_npc:preset/humanoid_slim/nalia_mom.npc.snbt
   *   legacy "cobblemon_initiative:humanoid/x" → easy_npc:preset/humanoid/x.npc.snbt
   * </pre>
   */
  public static String resolvePresetLocation(String raw) {
    String path = raw.contains(":") ? raw.substring(raw.indexOf(':') + 1) : raw;
    if (path.startsWith("easy_npc/default_preset/")) {
      path = path.substring("easy_npc/default_preset/".length());
    }
    if (path.startsWith(PRESET_PREFIX)) {
      path = path.substring(PRESET_PREFIX.length());
    }
    if (path.endsWith(PRESET_SUFFIX)) {
      path = path.substring(0, path.length() - PRESET_SUFFIX.length());
    }
    if (!path.contains("/")) {
      path = "humanoid/" + path;
    }
    return PRESET_NAMESPACE + ":" + PRESET_PREFIX + path + PRESET_SUFFIX;
  }

  private static boolean isEasyNpcPresent() {
    if (easyNpcPresent == null) {
      easyNpcPresent = FabricLoader.getInstance().isModLoaded("easynpc")
        || FabricLoader.getInstance().isModLoaded("easy_npc");
    }
    return easyNpcPresent;
  }
}
