# engage_scorchspire_leader — opens the Leader Vulcan battle after the challenge
# intro cutscene (battle.intro_scene). AUTO-GENERATED by scripts/content_compile
# — edit the character JSON, not this file. Runs AS the challenger from the
# scene's endBack stage position; the cutscene end-funnel fires it on skip too.
execute if entity b935a014-b7ed-4879-b6cb-f76c2a064a28 run tbcs attach rctmod:scorchspire_leader b935a014-b7ed-4879-b6cb-f76c2a064a28
tbcs battle GEN_9_SINGLES @s vs rctmod:scorchspire_leader onwin {1: ['cobbledollars give @1 6000', 'tag @1 add defeated_scorchspire_leader', '@2 say You walked into the fire and came out hotter than the spire. Carry the Ember Badge — and the machine in your bag holds Flamethrower. Nothing stands between you and the Royal League now but the road.', 'tag @1 remove scorchspire_forging'], 2: ['@1 say Fire does not forgive the unready. You burned bright but you burned out. Bank your coals and climb the spire again.', 'tag @2 remove scorchspire_forging']}
