# engage_royal_elite_3 — opens the Elite Four Luna battle after the challenge
# intro cutscene (battle.intro_scene). AUTO-GENERATED by scripts/content_compile
# — edit the character JSON, not this file. Runs AS the challenger from the
# scene's endBack stage position; the cutscene end-funnel fires it on skip too.
tbcs battle GEN_9_SINGLES @s vs rctmod:royal_elite_3 onwin {1: ['cobbledollars give @1 8000', 'tag @1 add defeated_royal_elite_3', '@2 say Even darkness has a shape, and you found it. Drake is last of the four. Do not let him intimidate you.'], 2: ['@1 say You lost the thread in the gloom. Find it again, and we will dance once more.']}
