# engage_nifl_leader_weak — opens the Leader Boreas battle after the challenge
# intro cutscene (battle.intro_scene). AUTO-GENERATED by scripts/content_compile
# — edit the character JSON, not this file. Runs AS the challenger from the
# scene's endBack stage position; the cutscene end-funnel fires it on skip too.
execute if entity cc1f6d46-48c1-42f2-bf46-a07194593733 run tbcs attach rctmod:nifl_leader_weak cc1f6d46-48c1-42f2-bf46-a07194593733
tbcs battle GEN_9_SINGLES @s vs rctmod:nifl_leader_weak onwin {1: ['cobbledollars give @1 5400', 'tag @1 add defeated_nifl_leader', '@2 say Cold sharpens what it does not kill. You came through clear and unbroken. The Glacier Badge is yours, and Ice Beam beside it.'], 2: ['@1 say The frost takes the hurried and the warm. Slow down. Go still. The ice will teach you, if you let it.']}
