# engage_takehara_leader_weak — opens the Leader Cicada battle after the challenge
# intro cutscene (battle.intro_scene). AUTO-GENERATED by scripts/content_compile
# — edit the character JSON, not this file. Runs AS the challenger from the
# scene's endBack stage position; the cutscene end-funnel fires it on skip too.
execute if entity c577141c-305f-4c20-a6bb-444d3b4d5ae0 run tbcs attach rctmod:takehara_leader_weak c577141c-305f-4c20-a6bb-444d3b4d5ae0
tbcs battle GEN_9_SINGLES @s vs rctmod:takehara_leader_weak onwin {1: ['cobbledollars give @1 1200', 'tag @1 add defeated_takehara_leader', '@2 say Patience wins. The machine in your bag holds U-turn — strike once, then be gone. Carry both to the next gym.'], 2: ['@1 say The woods will still be here. So will I. Come back ready.']}
