# engage_royal_champion — opens the Champion Cynthia battle after the challenge
# intro cutscene (battle.intro_scene). AUTO-GENERATED by scripts/content_compile
# — edit the character JSON, not this file. Runs AS the challenger from the
# scene's endBack stage position; the cutscene end-funnel fires it on skip too.
tbcs battle GEN_9_SINGLES @s vs rctmod:royal_champion onwin {1: ['cobbledollars give @1 12000', 'tag @1 add royal_league_champion', '@2 say So the throne goes to the one who built thrones. I always wondered who you would be when you remembered.'], 2: ['@1 say Not yet. The seat keeps itself for the one who can hold it. Come back when you are ready to take what is yours.']}
