# engage_royal_elite_2 — opens the Elite Four Marcus battle after the challenge
# intro cutscene (battle.intro_scene). AUTO-GENERATED by scripts/content_compile
# — edit the character JSON, not this file. Runs AS the challenger from the
# scene's endBack stage position; the cutscene end-funnel fires it on skip too.
tbcs battle GEN_9_SINGLES @s vs rctmod:royal_elite_2 onwin {1: ['cobbledollars give @1 6500', 'tag @1 add defeated_royal_elite_2', '@2 say Stone yields to the steady hand. You did not break against me. Luna waits in the cold hall.'], 2: ['@1 say You hit hard, but the mountain hits back. Come again when you can outlast it.']}
