# engage_mystic_leader_mirror_fire — opens the Leader Titania battle after the challenge
# intro cutscene (battle.intro_scene). AUTO-GENERATED by scripts/content_compile
# — edit the character JSON, not this file. Runs AS the challenger from the
# scene's endBack stage position; the cutscene end-funnel fires it on skip too.
execute if entity b665f300-628d-445b-8a3e-42a5cefca1bd run tbcs attach rctmod:mystic_leader_mirror_fire b665f300-628d-445b-8a3e-42a5cefca1bd
tbcs battle GEN_9_SINGLES @s vs rctmod:mystic_leader_mirror_fire onwin {1: ['cobbledollars give @1 2400', 'tag @1 add defeated_mystic_leader', '@2 say The marsh saw something true in you. So did I. Carry the Charm Badge — and the machine in your bag holds Moonblast. Let it speak for you when charm will not.'], 2: ['@1 say Charm is not enough here. Neither is force. Find the balance and the marsh will let you pass.']}
