# engage_cyber_leader_weak — opens the Leader Volt battle after the challenge
# intro cutscene (battle.intro_scene). AUTO-GENERATED by scripts/content_compile
# — edit the character JSON, not this file. Runs AS the challenger from the
# scene's endBack stage position; the cutscene end-funnel fires it on skip too.
execute if entity c839f20b-cffb-4103-87cc-cf57525a5ae7 run tbcs attach rctmod:cyber_leader_weak c839f20b-cffb-4103-87cc-cf57525a5ae7
tbcs battle GEN_9_SINGLES @s vs rctmod:cyber_leader_weak onwin {1: ['cobbledollars give @1 4300', 'tag @1 add defeated_cyber_leader', '@2 say Fast hands, faster head. You read the surge before it landed. Carry the Circuit Badge — and the machine in your bag holds Thunderbolt. Let it answer when charm will not.'], 2: ['@1 say Too slow on the draw. Electricity does not wait and neither do I. Sharpen up and reconnect with me.']}
