# engage_ryujin_leader — opens the Leader Ryujin battle after the challenge
# intro cutscene (battle.intro_scene). AUTO-GENERATED by scripts/content_compile
# — edit the character JSON, not this file. Runs AS the challenger from the
# scene's endBack stage position; the cutscene end-funnel fires it on skip too.
execute if entity 41d696fd-1824-4eaa-8b76-53f68095bafc run tbcs attach rctmod:ryujin_leader 41d696fd-1824-4eaa-8b76-53f68095bafc
tbcs battle GEN_9_SINGLES @s vs rctmod:ryujin_leader onwin {1: ['cobbledollars give @1 4900', 'tag @1 add defeated_ryujin_leader', '@2 say A dragon does not bow. You made it kneel anyway. Carry the Sovereign Badge - and the machine in your bag holds Dragon Pulse. Let it roar for you when your own voice will not.'], 2: ['@1 say Power without command is just noise. A dragon hears only those who do not flinch. Steel yourself and climb the Keep again.']}
