# engage_royal_elite_4 — opens the Elite Four Drake battle after the challenge
# intro cutscene (battle.intro_scene). AUTO-GENERATED by scripts/content_compile
# — edit the character JSON, not this file. Runs AS the challenger from the
# scene's endBack stage position; the cutscene end-funnel fires it on skip too.
tbcs battle GEN_9_SINGLES @s vs rctmod:royal_elite_4 onwin {1: ['cobbledollars give @1 9500', 'tag @1 add defeated_royal_elite_4', '@2 say Dragons bow to no one, and yet here you stand. Only the Champion remains. She has been watching, you know.'], 2: ['@1 say A dragon does not forgive a soft grip. Toughen up and try the storm again.']}
