# engage_royal_elite_1 — opens the Elite Four Aria battle after the challenge
# intro cutscene (battle.intro_scene). AUTO-GENERATED by scripts/content_compile
# — edit the character JSON, not this file. Runs AS the challenger from the
# scene's endBack stage position; the cutscene end-funnel fires it on skip too.
tbcs battle GEN_9_SINGLES @s vs rctmod:royal_elite_1 onwin {1: ['cobbledollars give @1 5000', 'tag @1 add defeated_royal_elite_1', '@2 say Shadows test the nerve before the mind. Yours did not flinch. Go on to Marcus.'], 2: ['@1 say The dark found the gap in your team. Mend it, and return when your nerve is whole.']}
