# engage_gaviota_leader — opens the Leader Neptune battle after the challenge
# intro cutscene (battle.intro_scene). AUTO-GENERATED by scripts/content_compile
# — edit the character JSON, not this file. Runs AS the challenger from the
# scene's endBack stage position; the cutscene end-funnel fires it on skip too.
execute if entity 0517452a-51a8-4a51-91e1-364a0c6765b6 run tbcs attach rctmod:gaviota_leader 0517452a-51a8-4a51-91e1-364a0c6765b6
tbcs battle GEN_9_SINGLES @s vs rctmod:gaviota_leader onwin {1: ['cobbledollars give @1 3200', 'tag @1 add defeated_gaviota_leader', '@2 say The tide turned and you turned with it. The Current Badge is yours, and Surf with it. The sea does not give either out lightly.'], 2: ['@1 say You fought the current head on. Nobody wins that way. Learn to ride it and the water will carry you back to me.']}
