# engage_deepcore_leader_weak — opens the Leader Bruno battle after the challenge
# intro cutscene (battle.intro_scene). AUTO-GENERATED by scripts/content_compile
# — edit the character JSON, not this file. Runs AS the challenger from the
# scene's endBack stage position; the cutscene end-funnel fires it on skip too.
execute if entity 4f016bc8-7b9f-4624-819d-149d93c688d3 run tbcs attach rctmod:deepcore_leader_weak 4f016bc8-7b9f-4624-819d-149d93c688d3
tbcs battle GEN_9_SINGLES @s vs rctmod:deepcore_leader_weak onwin {1: ['cobbledollars give @1 2800', 'tag @1 add defeated_deepcore_leader', '@2 say Now that is a punch with weight behind it. The Iron Badge is earned, not given. So is Drain Punch — the machine is yours. Take what you hit and keep it.'], 2: ['@1 say Get up. Always get up. The mat is not where you live. Train harder and find me again.']}
