# engage_kalahar_leader — opens the Leader Gaia battle after the challenge
# intro cutscene (battle.intro_scene). AUTO-GENERATED by scripts/content_compile
# — edit the character JSON, not this file. Runs AS the challenger from the
# scene's endBack stage position; the cutscene end-funnel fires it on skip too.
execute if entity e0fd76d6-c1d2-4101-9169-88a5f2aa59e2 run tbcs attach rctmod:kalahar_leader e0fd76d6-c1d2-4101-9169-88a5f2aa59e2
tbcs battle GEN_9_SINGLES @s vs rctmod:kalahar_leader onwin {1: ['cobbledollars give @1 3700', 'tag @1 add defeated_kalahar_leader', '@2 say Solid. Grounded. You do not get knocked off your feet, and that is half of everything. The Strata Badge is yours — and Earthquake, for ground that can take it.'], 2: ['@1 say The earth does not hurry and neither should you. Find your footing and dig back to me when you are ready.']}
