# update_npc_presets.mcfunction
# Auto-generated by generate_npc_function on 2026-05-31 16:27 UTC
# Source map: npc_presets.json
# Run with: /function cobblemon_initiative:update_npc_presets
# Requires permission level 2+
#
# Each line applies a preset to a specific in-world Easy NPC by UUID.
# Command: easy_npc preset import data <uuid> <resource_location>
