# update_npc_presets.mcfunction
# Auto-generated by generate_npc_function on 2026-07-03 16:16 UTC
# Source map: npc_presets.json
# Run with: /function cobblemon_initiative:update_npc_presets
# Requires permission level 2+
#
# Each line applies a preset to a specific in-world Easy NPC by UUID.
# Command: easy_npc preset import data <uuid> <resource_location>

# Dr. Aurelius Medcrest
easy_npc preset import data 0caa3fce-7b64-4a77-ba60-0be876cbb2f7 cobblemon_initiative:humanoid/aurelius_medcrest

# Helena Gatewarden
easy_npc preset import data 408f3e6d-921d-4891-a800-c1e70b0c7d30 cobblemon_initiative:humanoid/helena_gatewarden

# Lucian Scrollkeeper
easy_npc preset import data bdc36dd5-29ad-4d14-87d4-44ffa3f609e2 cobblemon_initiative:humanoid/lucian_scrollkeeper

# Roland Badgekeeper
easy_npc preset import data e5146ec2-ddc4-4b94-9469-1a8d95ccd497 cobblemon_initiative:humanoid/roland_badgekeeper

# Elder Nuru
easy_npc preset import data 306a81a0-1f5c-49a3-a126-3fae0e93fa23 cobblemon_initiative:humanoid/elder_nuru

# Elder Sentinel
easy_npc preset import data 277f717f-b441-4337-83be-62e14cb169a9 cobblemon_initiative:humanoid/elder_sentinel

# Nalia
easy_npc preset import data 74b1c524-0c3c-4a19-943d-f6f05c0e7f94 cobblemon_initiative:humanoid/nalia_mom

# Professor Acacia
easy_npc preset import data 92d33528-ab37-49a9-8761-241140d9b092 cobblemon_initiative:humanoid/professor_acacia
