# update_npc_presets.mcfunction
# Auto-generated by generate_npc_function on 2026-07-11 14:58 UTC
# Source map: npc_presets.json
# Run with: /function cobblemon_initiative:update_npc_presets
# Requires permission level 2+
#
# Each line applies a preset to a specific LOADED in-world Easy NPC by UUID.
# Grammar (Easy NPC 6.25): easy_npc preset import data <location> [<x y z> [<uuid>]]
# — the UUID is only accepted after a position, so each line runs as the NPC
# and passes ~ ~ ~. Unloaded NPCs are skipped (importing them would spawn a
# duplicate); the mod's NpcPresetRefreshManager covers those as chunks load.

# Helena Gatewarden
execute as 408f3e6d-921d-4891-a800-c1e70b0c7d30 at @s run easy_npc preset import data easy_npc:preset/humanoid/helena_gatewarden.npc.snbt ~ ~ ~ 408f3e6d-921d-4891-a800-c1e70b0c7d30

# Roland Badgekeeper
execute as e5146ec2-ddc4-4b94-9469-1a8d95ccd497 at @s run easy_npc preset import data easy_npc:preset/humanoid/roland_badgekeeper.npc.snbt ~ ~ ~ e5146ec2-ddc4-4b94-9469-1a8d95ccd497

# Elder Nuru
execute as 306a81a0-1f5c-49a3-a126-3fae0e93fa23 at @s run easy_npc preset import data easy_npc:preset/humanoid/elder_nuru.npc.snbt ~ ~ ~ 306a81a0-1f5c-49a3-a126-3fae0e93fa23

# Elder Sentinel
execute as 277f717f-b441-4337-83be-62e14cb169a9 at @s run easy_npc preset import data easy_npc:preset/humanoid/elder_sentinel.npc.snbt ~ ~ ~ 277f717f-b441-4337-83be-62e14cb169a9

# Nalia
execute as 74b1c524-0c3c-4a19-943d-f6f05c0e7f94 at @s run easy_npc preset import data easy_npc:preset/humanoid_slim/nalia_mom.npc.snbt ~ ~ ~ 74b1c524-0c3c-4a19-943d-f6f05c0e7f94

# Professor Acacia
execute as 92d33528-ab37-49a9-8761-241140d9b092 at @s run easy_npc preset import data easy_npc:preset/humanoid/professor_acacia.npc.snbt ~ ~ ~ 92d33528-ab37-49a9-8761-241140d9b092

# Takehara Gym Guide
execute as 58a64444-c674-49b4-9b21-965b634b41f5 at @s run easy_npc preset import data easy_npc:preset/humanoid_slim/takehara_guide.npc.snbt ~ ~ ~ 58a64444-c674-49b4-9b21-965b634b41f5

# Leader Cicada
execute as c577141c-305f-4c20-a6bb-444d3b4d5ae0 at @s run easy_npc preset import data easy_npc:preset/humanoid/takehara_leader.npc.snbt ~ ~ ~ c577141c-305f-4c20-a6bb-444d3b4d5ae0

# Zola
execute as 4db98c02-4445-4162-a2ac-a80c4cd4f685 at @s run easy_npc preset import data easy_npc:preset/humanoid_slim/sq_regular_4.npc.snbt ~ ~ ~ 4db98c02-4445-4162-a2ac-a80c4cd4f685

# Jabari
execute as dfd6ef2c-028e-403c-ac0e-3e77149fea30 at @s run easy_npc preset import data easy_npc:preset/humanoid/sq_regular_meadow.npc.snbt ~ ~ ~ dfd6ef2c-028e-403c-ac0e-3e77149fea30

# Bird Keeper Ayo
execute as 4637e716-e0e0-48f0-9359-c9c2292574c5 at @s run easy_npc preset import data easy_npc:preset/humanoid/sq_regular_spotter.npc.snbt ~ ~ ~ 4637e716-e0e0-48f0-9359-c9c2292574c5

# Bird Keeper Kwame
execute as 932ba1f1-fd1f-4ea4-837f-dcc16bf0bf4b at @s run easy_npc preset import data easy_npc:preset/humanoid/sq_regular_typetip.npc.snbt ~ ~ ~ 932ba1f1-fd1f-4ea4-837f-dcc16bf0bf4b

# Dr. Asha
execute as a9eeba58-7f9e-4fdc-803a-a4d12c9eb890 at @s run easy_npc preset import data easy_npc:preset/humanoid_slim/aurelius_medcrest.npc.snbt ~ ~ ~ a9eeba58-7f9e-4fdc-803a-a4d12c9eb890

# Lucian Scrollkeeper
execute as 7aeca5b3-1f72-4072-a8c4-e6eef877f160 at @s run easy_npc preset import data easy_npc:preset/humanoid_slim/lucian_scrollkeeper.npc.snbt ~ ~ ~ 7aeca5b3-1f72-4072-a8c4-e6eef877f160

# Kesi
execute as 21267950-7513-4328-81c9-e4dbed59678e at @s run easy_npc preset import data easy_npc:preset/humanoid/kesi.npc.snbt ~ ~ ~ 21267950-7513-4328-81c9-e4dbed59678e

# Jelani
execute as f63c8581-cfc3-474b-8484-2d6e4bd36b8f at @s run easy_npc preset import data easy_npc:preset/humanoid/auditor_b.npc.snbt ~ ~ ~ f63c8581-cfc3-474b-8484-2d6e4bd36b8f

# Imani
execute as 615697a6-44c4-47ba-8931-c5d767c7a29f at @s run easy_npc preset import data easy_npc:preset/humanoid/census_taker.npc.snbt ~ ~ ~ 615697a6-44c4-47ba-8931-c5d767c7a29f

# Reedhand Lumo
execute as f456a56a-a57b-4597-99a0-947688e91a4c at @s run easy_npc preset import data easy_npc:preset/humanoid/lumo.npc.snbt ~ ~ ~ f456a56a-a57b-4597-99a0-947688e91a4c

# Dakarai
execute as cd6f2588-e8c3-43f4-af3c-75f2f73e6535 at @s run easy_npc preset import data easy_npc:preset/humanoid/dakarai.npc.snbt ~ ~ ~ cd6f2588-e8c3-43f4-af3c-75f2f73e6535

# Deka
execute as 0d01e22f-451b-43dd-ba99-9250861f1872 at @s run easy_npc preset import data easy_npc:preset/humanoid/deka.npc.snbt ~ ~ ~ 0d01e22f-451b-43dd-ba99-9250861f1872

# Fara
execute as 4feff885-73d6-4856-bac5-737e36842e17 at @s run easy_npc preset import data easy_npc:preset/humanoid_slim/fara.npc.snbt ~ ~ ~ 4feff885-73d6-4856-bac5-737e36842e17

# Kele
execute as cdaa2a8e-7324-43d2-86d9-2266224b54ff at @s run easy_npc preset import data easy_npc:preset/humanoid/kele.npc.snbt ~ ~ ~ cdaa2a8e-7324-43d2-86d9-2266224b54ff

# Net-Mender Kima
execute as 66fab0ee-0531-4393-ab19-cfe80d9d3687 at @s run easy_npc preset import data easy_npc:preset/humanoid/kima.npc.snbt ~ ~ ~ 66fab0ee-0531-4393-ab19-cfe80d9d3687

# Kofi
execute as ad6f71d1-e7d6-42ca-a0ee-0e2be1bef45c at @s run easy_npc preset import data easy_npc:preset/humanoid/kofi.npc.snbt ~ ~ ~ ad6f71d1-e7d6-42ca-a0ee-0e2be1bef45c

# Assistant Miri
execute as 7a5cb32f-5bce-452d-b9cf-338ea381fe61 at @s run easy_npc preset import data easy_npc:preset/humanoid_slim/miri.npc.snbt ~ ~ ~ 7a5cb32f-5bce-452d-b9cf-338ea381fe61

# Oma
execute as ebfcb5e4-47a9-4c89-88fb-fed3a9e06a42 at @s run easy_npc preset import data easy_npc:preset/humanoid_slim/oma.npc.snbt ~ ~ ~ ebfcb5e4-47a9-4c89-88fb-fed3a9e06a42

# Assistant Raan
execute as 87c0a388-7823-451b-a394-02d537bbcc65 at @s run easy_npc preset import data easy_npc:preset/humanoid/raan.npc.snbt ~ ~ ~ 87c0a388-7823-451b-a394-02d537bbcc65

# Old Sefu
execute as 66597678-01cb-4d1c-815c-b4d247cfeaa1 at @s run easy_npc preset import data easy_npc:preset/humanoid/sefu.npc.snbt ~ ~ ~ 66597678-01cb-4d1c-815c-b4d247cfeaa1

# Marlow
execute as 26aeda15-0f97-4adc-b502-787e666d7429 at @s run easy_npc preset import data easy_npc:preset/humanoid_slim/sq_uncle_marlow.npc.snbt ~ ~ ~ 26aeda15-0f97-4adc-b502-787e666d7429

# Pondwarden Tayo
execute as 6f358087-9ecb-4859-9d39-519b66f4817f at @s run easy_npc preset import data easy_npc:preset/humanoid/tayo.npc.snbt ~ ~ ~ 6f358087-9ecb-4859-9d39-519b66f4817f

# Apprentice Aiko
execute as 53facfa6-2697-4d4c-9f7f-58bbeb10fbf1 at @s run easy_npc preset import data easy_npc:preset/humanoid_slim/apprentice_aiko.npc.snbt ~ ~ ~ 53facfa6-2697-4d4c-9f7f-58bbeb10fbf1

# Kazuo
execute as 77d7fb8d-a289-4b8c-a275-1333dd3226d8 at @s run easy_npc preset import data easy_npc:preset/humanoid/company_canvasser.npc.snbt ~ ~ ~ 77d7fb8d-a289-4b8c-a275-1333dd3226d8

# Curator Kenji
execute as 41d04e62-b0ec-4ab6-95f9-da51d8516ee7 at @s run easy_npc preset import data easy_npc:preset/humanoid/curator_tamiko.npc.snbt ~ ~ ~ 41d04e62-b0ec-4ab6-95f9-da51d8516ee7

# Falls Warden Shou
execute as 8cbc3a47-7a69-4440-bab2-325766eb889b at @s run easy_npc preset import data easy_npc:preset/humanoid/falls_warden_ayame.npc.snbt ~ ~ ~ 8cbc3a47-7a69-4440-bab2-325766eb889b

# Jr. Apprentice Sora
execute as b454a1b1-e72b-4de0-8c13-f72e0ed3733d at @s run easy_npc preset import data easy_npc:preset/humanoid_slim/jr_apprentice_sora.npc.snbt ~ ~ ~ b454a1b1-e72b-4de0-8c13-f72e0ed3733d

# Mayor Liang
execute as 29a584e7-0751-4ba6-b9e3-214c00d2b5fc at @s run easy_npc preset import data easy_npc:preset/humanoid/mayor_suzune.npc.snbt ~ ~ ~ 29a584e7-0751-4ba6-b9e3-214c00d2b5fc

# Sayuri
execute as 4f705354-bc3f-4eef-bb16-396822b6cf52 at @s run easy_npc preset import data easy_npc:preset/humanoid_slim/museum_sayuri.npc.snbt ~ ~ ~ 4f705354-bc3f-4eef-bb16-396822b6cf52

# Nurse Lila
execute as 8c164050-23a7-47b8-8da7-0c79c340e696 at @s run easy_npc preset import data easy_npc:preset/humanoid_slim/nurse_lila.npc.snbt ~ ~ ~ 8c164050-23a7-47b8-8da7-0c79c340e696

# Printmaker Mei
execute as 59463ac9-41bb-4174-b4af-99d1c92ad158 at @s run easy_npc preset import data easy_npc:preset/humanoid_slim/printmaker_ume.npc.snbt ~ ~ ~ 59463ac9-41bb-4174-b4af-99d1c92ad158

# Trader Mayu
execute as 3666562e-8bcb-4db0-9e94-1c23ab234e2b at @s run easy_npc preset import data easy_npc:preset/humanoid_slim/trader_mayu.npc.snbt ~ ~ ~ 3666562e-8bcb-4db0-9e94-1c23ab234e2b

# Beekeeper Masumi
execute as abd658e4-8471-4812-9ffb-40e48cc9c249 at @s run easy_npc preset import data easy_npc:preset/humanoid/beekeeper_masumi.npc.snbt ~ ~ ~ abd658e4-8471-4812-9ffb-40e48cc9c249

# Fisherman Genji
execute as 6b050c04-5eb8-40f4-aead-716abab6af50 at @s run easy_npc preset import data easy_npc:preset/humanoid_slim/fisherman_genji.npc.snbt ~ ~ ~ 6b050c04-5eb8-40f4-aead-716abab6af50

# Beekeeper Tomo
execute as 4e3a8cf1-e57f-4666-aed5-4e51f8b6b020 at @s run easy_npc preset import data easy_npc:preset/humanoid/sq_beekeeper_tomo.npc.snbt ~ ~ ~ 4e3a8cf1-e57f-4666-aed5-4e51f8b6b020

# Garden Master Wei
execute as f4db3d54-eb9d-419c-8527-f7244e7bfcff at @s run easy_npc preset import data easy_npc:preset/humanoid/garden_master_wei.npc.snbt ~ ~ ~ f4db3d54-eb9d-419c-8527-f7244e7bfcff

# Groundskeeper Aya
execute as a9ed3a64-f69f-4a0f-a483-afb5706e5d4f at @s run easy_npc preset import data easy_npc:preset/humanoid/groundskeeper_aya.npc.snbt ~ ~ ~ a9ed3a64-f69f-4a0f-a483-afb5706e5d4f

# Branch Manager Chen Bao
execute as 4bb297e2-73e4-4888-b970-970105e6fc42 at @s run easy_npc preset import data easy_npc:preset/humanoid/hz_branch_manager.npc.snbt ~ ~ ~ 4bb297e2-73e4-4888-b970-970105e6fc42

# Kaito Zhang
execute as 7550e0ca-5064-4437-a2ab-a310305e3bf4 at @s run easy_npc preset import data easy_npc:preset/humanoid/hz_martkeeper.npc.snbt ~ ~ ~ 7550e0ca-5064-4437-a2ab-a310305e3bf4

# Nurse Anong
execute as 00682844-c22d-4359-a797-0b55f44a94bc at @s run easy_npc preset import data easy_npc:preset/humanoid/hz_nurse.npc.snbt ~ ~ ~ 00682844-c22d-4359-a797-0b55f44a94bc

# Linh Hua
execute as 1c06d60f-a97e-49a0-b0e6-fede9deaa00e at @s run easy_npc preset import data easy_npc:preset/humanoid/hz_stall_linh.npc.snbt ~ ~ ~ 1c06d60f-a97e-49a0-b0e6-fede9deaa00e

# Mei Lin
execute as 40d88258-2eed-4cb8-afc4-6f7edf77d69c at @s run easy_npc preset import data easy_npc:preset/humanoid/hz_stall_mei.npc.snbt ~ ~ ~ 40d88258-2eed-4cb8-afc4-6f7edf77d69c

# Wei Shun
execute as b158bfc2-ebad-4b40-ae56-4b55974e06cb at @s run easy_npc preset import data easy_npc:preset/humanoid/hz_stall_wei.npc.snbt ~ ~ ~ b158bfc2-ebad-4b40-ae56-4b55974e06cb

# Deng Haoran
execute as 42c16f04-777c-4512-9b05-50a6c726a1cf at @s run easy_npc preset import data easy_npc:preset/humanoid/deng_haoran.npc.snbt ~ ~ ~ 42c16f04-777c-4512-9b05-50a6c726a1cf

# Harvest Hand Luo Shiming
execute as 7063a903-35cd-4b76-8a6d-962225105793 at @s run easy_npc preset import data easy_npc:preset/humanoid/luo_shiming.npc.snbt ~ ~ ~ 7063a903-35cd-4b76-8a6d-962225105793

# Scarecrow Wrangler Mirek
execute as ae9aa285-8251-46db-a520-ab00dab02a21 at @s run easy_npc preset import data easy_npc:preset/humanoid/mirek.npc.snbt ~ ~ ~ ae9aa285-8251-46db-a520-ab00dab02a21

# Kite Runner Xu Jianyu
execute as 535c306c-cb90-43c1-a405-e84099a01b8d at @s run easy_npc preset import data easy_npc:preset/humanoid/xu_jianyu.npc.snbt ~ ~ ~ 535c306c-cb90-43c1-a405-e84099a01b8d

# Hua Zhan Gym Guide
execute as 7100a6fc-d123-4d9b-9140-b4d37db50975 at @s run easy_npc preset import data easy_npc:preset/humanoid/hua_zhan_guide.npc.snbt ~ ~ ~ 7100a6fc-d123-4d9b-9140-b4d37db50975

# Shu
execute as dd432f28-7cbd-42a1-a617-d33eec10a7eb at @s run easy_npc preset import data easy_npc:preset/humanoid/hz_greenhouse_archivist.npc.snbt ~ ~ ~ dd432f28-7cbd-42a1-a617-d33eec10a7eb

# Bo
execute as a9bebc53-64b7-4466-a08c-84101ab9809a at @s run easy_npc preset import data easy_npc:preset/humanoid/hz_greenhouse_greeter.npc.snbt ~ ~ ~ a9bebc53-64b7-4466-a08c-84101ab9809a

# Rong
execute as f45f3fda-5de3-4f69-9485-e4a8f5df225f at @s run easy_npc preset import data easy_npc:preset/humanoid/hz_greenhouse_overseer.npc.snbt ~ ~ ~ f45f3fda-5de3-4f69-9485-e4a8f5df225f

# Guo the Miller
execute as 379e0fdb-36eb-4173-8297-d209a031027d at @s run easy_npc preset import data easy_npc:preset/humanoid/hz_miller.npc.snbt ~ ~ ~ 379e0fdb-36eb-4173-8297-d209a031027d

# Feng
# (skipped: granary tier pipeline owns this NPC — easy_npc:preset/humanoid/granary_keeper.npc.snbt)

# Ping
execute as 0f011555-0a8b-4924-aea9-42a06b5b72c9 at @s run easy_npc preset import data easy_npc:preset/humanoid/wheat_trader_1.npc.snbt ~ ~ ~ 0f011555-0a8b-4924-aea9-42a06b5b72c9

# Tau
execute as 45240216-2c97-4a78-af13-37ed427040ee at @s run easy_npc preset import data easy_npc:preset/humanoid/wheat_trader_2.npc.snbt ~ ~ ~ 45240216-2c97-4a78-af13-37ed427040ee

# Leader Titania
execute as b665f300-628d-445b-8a3e-42a5cefca1bd at @s run easy_npc preset import data easy_npc:preset/humanoid/mystic_leader.npc.snbt ~ ~ ~ b665f300-628d-445b-8a3e-42a5cefca1bd

# Leader Volt
execute as c839f20b-cffb-4103-87cc-cf57525a5ae7 at @s run easy_npc preset import data easy_npc:preset/humanoid/cyber_leader.npc.snbt ~ ~ ~ c839f20b-cffb-4103-87cc-cf57525a5ae7

# Leader Bruno
execute as 4f016bc8-7b9f-4624-819d-149d93c688d3 at @s run easy_npc preset import data easy_npc:preset/humanoid/deepcore_leader.npc.snbt ~ ~ ~ 4f016bc8-7b9f-4624-819d-149d93c688d3

# Leader Neptune
execute as 0517452a-51a8-4a51-91e1-364a0c6765b6 at @s run easy_npc preset import data easy_npc:preset/humanoid/gaviota_leader.npc.snbt ~ ~ ~ 0517452a-51a8-4a51-91e1-364a0c6765b6

# Leader Gaia
execute as e0fd76d6-c1d2-4101-9169-88a5f2aa59e2 at @s run easy_npc preset import data easy_npc:preset/humanoid/kalahar_leader.npc.snbt ~ ~ ~ e0fd76d6-c1d2-4101-9169-88a5f2aa59e2

# Leader Boreas
execute as cc1f6d46-48c1-42f2-bf46-a07194593733 at @s run easy_npc preset import data easy_npc:preset/humanoid/nifl_leader.npc.snbt ~ ~ ~ cc1f6d46-48c1-42f2-bf46-a07194593733

# Leader Ryujin
execute as 41d696fd-1824-4eaa-8b76-53f68095bafc at @s run easy_npc preset import data easy_npc:preset/humanoid/ryujin_leader.npc.snbt ~ ~ ~ 41d696fd-1824-4eaa-8b76-53f68095bafc

# Leader Vulcan
execute as b935a014-b7ed-4879-b6cb-f76c2a064a28 at @s run easy_npc preset import data easy_npc:preset/humanoid/scorchspire_leader.npc.snbt ~ ~ ~ b935a014-b7ed-4879-b6cb-f76c2a064a28
