# band_tags — derive threshold PLAYER_TAGs from scoreboards for Easy NPC dialog gates.
# Auto-generated by scripts/content_compile. Add to your tick function tag.
# Easy NPC dialog Conditions only reliably support PLAYER_TAG, so numeric gates
# (badges/cd_instability/fields_liberated/recognition) are lowered to these tags.
# Single-player: @a == the player; idempotent add/remove keeps it relog-safe.

execute as @a if score @s memory_fragment matches 10.. run tag @s add badges_gte_10
execute as @a unless score @s memory_fragment matches 10.. run tag @s remove badges_gte_10

execute as @a if score @s memory_fragment matches 3.. run tag @s add badges_gte_3
execute as @a unless score @s memory_fragment matches 3.. run tag @s remove badges_gte_3

execute as @a if score @s memory_fragment matches 7.. run tag @s add badges_gte_7
execute as @a unless score @s memory_fragment matches 7.. run tag @s remove badges_gte_7

execute as @a if score @s cd_instability matches 40.. run tag @s add cd_instability_gte_40
execute as @a unless score @s cd_instability matches 40.. run tag @s remove cd_instability_gte_40

