# band_tags — derive PLAYER_TAGs for Easy NPC dialog gates.
# Auto-generated by scripts/content_compile. Add to your tick function tag.
# Two families:
#   1. numeric threshold tags (badges/cd_instability/fields_liberated/recognition)
#   2. inverse tags no_<X> — Easy NPC 6.25's PLAYER_TAG condition IGNORES the
#      Operation field (bytecode: contains() only), so NOT_EQUALS cannot express
#      "does not have the tag"; every not-gate rides EQUALS no_<X> instead.
# Single-player: @a == the player; idempotent add/remove keeps it relog-safe.

execute as @a if score @s memory_fragment matches 1.. run tag @s add badges_gte_1
execute as @a unless score @s memory_fragment matches 1.. run tag @s remove badges_gte_1

execute as @a if score @s memory_fragment matches 10.. run tag @s add badges_gte_10
execute as @a unless score @s memory_fragment matches 10.. run tag @s remove badges_gte_10

execute as @a if score @s memory_fragment matches 2.. run tag @s add badges_gte_2
execute as @a unless score @s memory_fragment matches 2.. run tag @s remove badges_gte_2

execute as @a if score @s memory_fragment matches 3.. run tag @s add badges_gte_3
execute as @a unless score @s memory_fragment matches 3.. run tag @s remove badges_gte_3

execute as @a if score @s memory_fragment matches 4.. run tag @s add badges_gte_4
execute as @a unless score @s memory_fragment matches 4.. run tag @s remove badges_gte_4

execute as @a if score @s memory_fragment matches 7.. run tag @s add badges_gte_7
execute as @a unless score @s memory_fragment matches 7.. run tag @s remove badges_gte_7

execute as @a if score @s memory_fragment matches ..2 run tag @s add badges_lt_3
execute as @a unless score @s memory_fragment matches ..2 run tag @s remove badges_lt_3

execute as @a if score @s cd_instability matches 16.. run tag @s add cd_instability_gte_16
execute as @a unless score @s cd_instability matches 16.. run tag @s remove cd_instability_gte_16

execute as @a if score @s cd_instability matches 20.. run tag @s add cd_instability_gte_20
execute as @a unless score @s cd_instability matches 20.. run tag @s remove cd_instability_gte_20

execute as @a if score @s cd_instability matches 40.. run tag @s add cd_instability_gte_40
execute as @a unless score @s cd_instability matches 40.. run tag @s remove cd_instability_gte_40

execute as @a if score @s cd_instability matches 8.. run tag @s add cd_instability_gte_8
execute as @a unless score @s cd_instability matches 8.. run tag @s remove cd_instability_gte_8

execute as @a if score @s ci_notices matches 3.. run tag @s add ci_notices_gte_3
execute as @a unless score @s ci_notices matches 3.. run tag @s remove ci_notices_gte_3

execute as @a if score @s ci_papers_filed matches 3.. run tag @s add ci_papers_filed_gte_3
execute as @a unless score @s ci_papers_filed matches 3.. run tag @s remove ci_papers_filed_gte_3

execute as @a if score @s ci_papers_filed matches 6.. run tag @s add ci_papers_filed_gte_6
execute as @a unless score @s ci_papers_filed matches 6.. run tag @s remove ci_papers_filed_gte_6

execute as @a if score @s dex_caught matches 15.. run tag @s add dex_gte_15
execute as @a unless score @s dex_caught matches 15.. run tag @s remove dex_gte_15

execute as @a if score @s dex_caught matches 2.. run tag @s add dex_gte_2
execute as @a unless score @s dex_caught matches 2.. run tag @s remove dex_gte_2

execute as @a if score @s dex_caught matches 30.. run tag @s add dex_gte_30
execute as @a unless score @s dex_caught matches 30.. run tag @s remove dex_gte_30

execute as @a if score @s fields_liberated matches 1.. run tag @s add fields_liberated_gte_1
execute as @a unless score @s fields_liberated matches 1.. run tag @s remove fields_liberated_gte_1

execute as @a if score @s fields_liberated matches 2.. run tag @s add fields_liberated_gte_2
execute as @a unless score @s fields_liberated matches 2.. run tag @s remove fields_liberated_gte_2

execute as @a if score @s fields_liberated matches 4.. run tag @s add fields_liberated_gte_4
execute as @a unless score @s fields_liberated matches 4.. run tag @s remove fields_liberated_gte_4

execute as @a if score @s hz_market matches 1 run tag @s add hz_market_eq_1
execute as @a unless score @s hz_market matches 1 run tag @s remove hz_market_eq_1

execute as @a if score @s hz_market matches 2 run tag @s add hz_market_eq_2
execute as @a unless score @s hz_market matches 2 run tag @s remove hz_market_eq_2

execute as @a if score @s memory_fragment matches ..2 run tag @s add memory_fragment_lt_3
execute as @a unless score @s memory_fragment matches ..2 run tag @s remove memory_fragment_lt_3

execute as @a if score @s takehara_tower matches 1.. run tag @s add takehara_tower_gte_1
execute as @a unless score @s takehara_tower matches 1.. run tag @s remove takehara_tower_gte_1

execute as @a if score @s takehara_tower matches 2.. run tag @s add takehara_tower_gte_2
execute as @a unless score @s takehara_tower matches 2.. run tag @s remove takehara_tower_gte_2

execute as @a if score @s takehara_tower matches 4.. run tag @s add takehara_tower_gte_4
execute as @a unless score @s takehara_tower matches 4.. run tag @s remove takehara_tower_gte_4

# inverse tags (no_<X> == player does NOT have X)
tag @a[tag=!assist_coal_in] add no_assist_coal_in
tag @a[tag=assist_coal_in] remove no_assist_coal_in
tag @a[tag=!assist_iron_in] add no_assist_iron_in
tag @a[tag=assist_iron_in] remove no_assist_iron_in
tag @a[tag=!bought_magikarp] add no_bought_magikarp
tag @a[tag=bought_magikarp] remove no_bought_magikarp
tag @a[tag=!census_accepted] add no_census_accepted
tag @a[tag=census_accepted] remove no_census_accepted
tag @a[tag=!census_done] add no_census_done
tag @a[tag=census_done] remove no_census_done
tag @a[tag=!census_paid] add no_census_paid
tag @a[tag=census_paid] remove no_census_paid
tag @a[tag=!census_processed] add no_census_processed
tag @a[tag=census_processed] remove no_census_processed
tag @a[tag=!census_signed] add no_census_signed
tag @a[tag=census_signed] remove no_census_signed
tag @a[tag=!ci_starters_spawned] add no_ci_starters_spawned
tag @a[tag=ci_starters_spawned] remove no_ci_starters_spawned
tag @a[tag=!classic_active] add no_classic_active
tag @a[tag=classic_active] remove no_classic_active
tag @a[tag=!classic_rod_given] add no_classic_rod_given
tag @a[tag=classic_rod_given] remove no_classic_rod_given
tag @a[tag=!clinic_cheri_in] add no_clinic_cheri_in
tag @a[tag=clinic_cheri_in] remove no_clinic_cheri_in
tag @a[tag=!clinic_oran_in] add no_clinic_oran_in
tag @a[tag=clinic_oran_in] remove no_clinic_oran_in
tag @a[tag=!clinic_pecha_in] add no_clinic_pecha_in
tag @a[tag=clinic_pecha_in] remove no_clinic_pecha_in
tag @a[tag=!clinic_stocked] add no_clinic_stocked
tag @a[tag=clinic_stocked] remove no_clinic_stocked
tag @a[tag=!company_overthrown] add no_company_overthrown
tag @a[tag=company_overthrown] remove no_company_overthrown
tag @a[tag=!declined_sq_canvasser] add no_declined_sq_canvasser
tag @a[tag=declined_sq_canvasser] remove no_declined_sq_canvasser
tag @a[tag=!declined_sq_genji_wager] add no_declined_sq_genji_wager
tag @a[tag=declined_sq_genji_wager] remove no_declined_sq_genji_wager
tag @a[tag=!declined_sq_headcount_wager] add no_declined_sq_headcount_wager
tag @a[tag=declined_sq_headcount_wager] remove no_declined_sq_headcount_wager
tag @a[tag=!declined_sq_hz_analyst] add no_declined_sq_hz_analyst
tag @a[tag=declined_sq_hz_analyst] remove no_declined_sq_hz_analyst
tag @a[tag=!declined_sq_kyc_agent] add no_declined_sq_kyc_agent
tag @a[tag=declined_sq_kyc_agent] remove no_declined_sq_kyc_agent
tag @a[tag=!declined_sq_regular_4] add no_declined_sq_regular_4
tag @a[tag=declined_sq_regular_4] remove no_declined_sq_regular_4
tag @a[tag=!declined_sq_regular_meadow] add no_declined_sq_regular_meadow
tag @a[tag=declined_sq_regular_meadow] remove no_declined_sq_regular_meadow
tag @a[tag=!declined_sq_regular_spotter] add no_declined_sq_regular_spotter
tag @a[tag=declined_sq_regular_spotter] remove no_declined_sq_regular_spotter
tag @a[tag=!declined_sq_regular_typetip] add no_declined_sq_regular_typetip
tag @a[tag=declined_sq_regular_typetip] remove no_declined_sq_regular_typetip
tag @a[tag=!declined_sq_rt2_haoran] add no_declined_sq_rt2_haoran
tag @a[tag=declined_sq_rt2_haoran] remove no_declined_sq_rt2_haoran
tag @a[tag=!declined_sq_rt2_kite] add no_declined_sq_rt2_kite
tag @a[tag=declined_sq_rt2_kite] remove no_declined_sq_rt2_kite
tag @a[tag=!declined_sq_rt2_scarecrow] add no_declined_sq_rt2_scarecrow
tag @a[tag=declined_sq_rt2_scarecrow] remove no_declined_sq_rt2_scarecrow
tag @a[tag=!declined_sq_rt2_wager] add no_declined_sq_rt2_wager
tag @a[tag=declined_sq_rt2_wager] remove no_declined_sq_rt2_wager
tag @a[tag=!declined_villain_yield_analyst] add no_declined_villain_yield_analyst
tag @a[tag=declined_villain_yield_analyst] remove no_declined_villain_yield_analyst
tag @a[tag=!deed_read_lucian] add no_deed_read_lucian
tag @a[tag=deed_read_lucian] remove no_deed_read_lucian
tag @a[tag=!defeated_board_lauren] add no_defeated_board_lauren
tag @a[tag=defeated_board_lauren] remove no_defeated_board_lauren
tag @a[tag=!defeated_board_madeline] add no_defeated_board_madeline
tag @a[tag=defeated_board_madeline] remove no_defeated_board_madeline
tag @a[tag=!defeated_board_matt] add no_defeated_board_matt
tag @a[tag=defeated_board_matt] remove no_defeated_board_matt
tag @a[tag=!defeated_board_micah] add no_defeated_board_micah
tag @a[tag=defeated_board_micah] remove no_defeated_board_micah
tag @a[tag=!defeated_cyber_apprentice] add no_defeated_cyber_apprentice
tag @a[tag=defeated_cyber_apprentice] remove no_defeated_cyber_apprentice
tag @a[tag=!defeated_cyber_leader] add no_defeated_cyber_leader
tag @a[tag=defeated_cyber_leader] remove no_defeated_cyber_leader
tag @a[tag=!defeated_cyber_trainer_1] add no_defeated_cyber_trainer_1
tag @a[tag=defeated_cyber_trainer_1] remove no_defeated_cyber_trainer_1
tag @a[tag=!defeated_cyber_trainer_2] add no_defeated_cyber_trainer_2
tag @a[tag=defeated_cyber_trainer_2] remove no_defeated_cyber_trainer_2
tag @a[tag=!defeated_deepcore_apprentice] add no_defeated_deepcore_apprentice
tag @a[tag=defeated_deepcore_apprentice] remove no_defeated_deepcore_apprentice
tag @a[tag=!defeated_deepcore_leader] add no_defeated_deepcore_leader
tag @a[tag=defeated_deepcore_leader] remove no_defeated_deepcore_leader
tag @a[tag=!defeated_deepcore_trainer_1] add no_defeated_deepcore_trainer_1
tag @a[tag=defeated_deepcore_trainer_1] remove no_defeated_deepcore_trainer_1
tag @a[tag=!defeated_deepcore_trainer_2] add no_defeated_deepcore_trainer_2
tag @a[tag=defeated_deepcore_trainer_2] remove no_defeated_deepcore_trainer_2
tag @a[tag=!defeated_dragon_shrine_cultist_1] add no_defeated_dragon_shrine_cultist_1
tag @a[tag=defeated_dragon_shrine_cultist_1] remove no_defeated_dragon_shrine_cultist_1
tag @a[tag=!defeated_dragon_shrine_cultist_2] add no_defeated_dragon_shrine_cultist_2
tag @a[tag=defeated_dragon_shrine_cultist_2] remove no_defeated_dragon_shrine_cultist_2
tag @a[tag=!defeated_dragon_shrine_leader] add no_defeated_dragon_shrine_leader
tag @a[tag=defeated_dragon_shrine_leader] remove no_defeated_dragon_shrine_leader
tag @a[tag=!defeated_fairy_shrine_cultist_1] add no_defeated_fairy_shrine_cultist_1
tag @a[tag=defeated_fairy_shrine_cultist_1] remove no_defeated_fairy_shrine_cultist_1
tag @a[tag=!defeated_fairy_shrine_cultist_2] add no_defeated_fairy_shrine_cultist_2
tag @a[tag=defeated_fairy_shrine_cultist_2] remove no_defeated_fairy_shrine_cultist_2
tag @a[tag=!defeated_fairy_shrine_leader] add no_defeated_fairy_shrine_leader
tag @a[tag=defeated_fairy_shrine_leader] remove no_defeated_fairy_shrine_leader
tag @a[tag=!defeated_fire_shrine_cultist_1] add no_defeated_fire_shrine_cultist_1
tag @a[tag=defeated_fire_shrine_cultist_1] remove no_defeated_fire_shrine_cultist_1
tag @a[tag=!defeated_fire_shrine_cultist_2] add no_defeated_fire_shrine_cultist_2
tag @a[tag=defeated_fire_shrine_cultist_2] remove no_defeated_fire_shrine_cultist_2
tag @a[tag=!defeated_fire_shrine_leader] add no_defeated_fire_shrine_leader
tag @a[tag=defeated_fire_shrine_leader] remove no_defeated_fire_shrine_leader
tag @a[tag=!defeated_gaviota_apprentice] add no_defeated_gaviota_apprentice
tag @a[tag=defeated_gaviota_apprentice] remove no_defeated_gaviota_apprentice
tag @a[tag=!defeated_gaviota_leader] add no_defeated_gaviota_leader
tag @a[tag=defeated_gaviota_leader] remove no_defeated_gaviota_leader
tag @a[tag=!defeated_gaviota_trainer_1] add no_defeated_gaviota_trainer_1
tag @a[tag=defeated_gaviota_trainer_1] remove no_defeated_gaviota_trainer_1
tag @a[tag=!defeated_gaviota_trainer_2] add no_defeated_gaviota_trainer_2
tag @a[tag=defeated_gaviota_trainer_2] remove no_defeated_gaviota_trainer_2
tag @a[tag=!defeated_granary_ambush] add no_defeated_granary_ambush
tag @a[tag=defeated_granary_ambush] remove no_defeated_granary_ambush
tag @a[tag=!defeated_ground_shrine_cultist_1] add no_defeated_ground_shrine_cultist_1
tag @a[tag=defeated_ground_shrine_cultist_1] remove no_defeated_ground_shrine_cultist_1
tag @a[tag=!defeated_ground_shrine_cultist_2] add no_defeated_ground_shrine_cultist_2
tag @a[tag=defeated_ground_shrine_cultist_2] remove no_defeated_ground_shrine_cultist_2
tag @a[tag=!defeated_ground_shrine_leader] add no_defeated_ground_shrine_leader
tag @a[tag=defeated_ground_shrine_leader] remove no_defeated_ground_shrine_leader
tag @a[tag=!defeated_groundskeeper_aya] add no_defeated_groundskeeper_aya
tag @a[tag=defeated_groundskeeper_aya] remove no_defeated_groundskeeper_aya
tag @a[tag=!defeated_hua_zhan_apprentice] add no_defeated_hua_zhan_apprentice
tag @a[tag=defeated_hua_zhan_apprentice] remove no_defeated_hua_zhan_apprentice
tag @a[tag=!defeated_hua_zhan_jr_apprentice] add no_defeated_hua_zhan_jr_apprentice
tag @a[tag=defeated_hua_zhan_jr_apprentice] remove no_defeated_hua_zhan_jr_apprentice
tag @a[tag=!defeated_hua_zhan_leader] add no_defeated_hua_zhan_leader
tag @a[tag=defeated_hua_zhan_leader] remove no_defeated_hua_zhan_leader
tag @a[tag=!defeated_hua_zhan_trainer_1] add no_defeated_hua_zhan_trainer_1
tag @a[tag=defeated_hua_zhan_trainer_1] remove no_defeated_hua_zhan_trainer_1
tag @a[tag=!defeated_hua_zhan_trainer_2] add no_defeated_hua_zhan_trainer_2
tag @a[tag=defeated_hua_zhan_trainer_2] remove no_defeated_hua_zhan_trainer_2
tag @a[tag=!defeated_hua_zhan_trainer_3] add no_defeated_hua_zhan_trainer_3
tag @a[tag=defeated_hua_zhan_trainer_3] remove no_defeated_hua_zhan_trainer_3
tag @a[tag=!defeated_hua_zhan_trainer_4] add no_defeated_hua_zhan_trainer_4
tag @a[tag=defeated_hua_zhan_trainer_4] remove no_defeated_hua_zhan_trainer_4
tag @a[tag=!defeated_ice_shrine_cultist_1] add no_defeated_ice_shrine_cultist_1
tag @a[tag=defeated_ice_shrine_cultist_1] remove no_defeated_ice_shrine_cultist_1
tag @a[tag=!defeated_ice_shrine_cultist_2] add no_defeated_ice_shrine_cultist_2
tag @a[tag=defeated_ice_shrine_cultist_2] remove no_defeated_ice_shrine_cultist_2
tag @a[tag=!defeated_ice_shrine_leader] add no_defeated_ice_shrine_leader
tag @a[tag=defeated_ice_shrine_leader] remove no_defeated_ice_shrine_leader
tag @a[tag=!defeated_kalahar_apprentice] add no_defeated_kalahar_apprentice
tag @a[tag=defeated_kalahar_apprentice] remove no_defeated_kalahar_apprentice
tag @a[tag=!defeated_kalahar_leader] add no_defeated_kalahar_leader
tag @a[tag=defeated_kalahar_leader] remove no_defeated_kalahar_leader
tag @a[tag=!defeated_kalahar_trainer_1] add no_defeated_kalahar_trainer_1
tag @a[tag=defeated_kalahar_trainer_1] remove no_defeated_kalahar_trainer_1
tag @a[tag=!defeated_kalahar_trainer_2] add no_defeated_kalahar_trainer_2
tag @a[tag=defeated_kalahar_trainer_2] remove no_defeated_kalahar_trainer_2
tag @a[tag=!defeated_mystic_apprentice] add no_defeated_mystic_apprentice
tag @a[tag=defeated_mystic_apprentice] remove no_defeated_mystic_apprentice
tag @a[tag=!defeated_mystic_leader] add no_defeated_mystic_leader
tag @a[tag=defeated_mystic_leader] remove no_defeated_mystic_leader
tag @a[tag=!defeated_mystic_trainer_1] add no_defeated_mystic_trainer_1
tag @a[tag=defeated_mystic_trainer_1] remove no_defeated_mystic_trainer_1
tag @a[tag=!defeated_mystic_trainer_2] add no_defeated_mystic_trainer_2
tag @a[tag=defeated_mystic_trainer_2] remove no_defeated_mystic_trainer_2
tag @a[tag=!defeated_nifl_apprentice] add no_defeated_nifl_apprentice
tag @a[tag=defeated_nifl_apprentice] remove no_defeated_nifl_apprentice
tag @a[tag=!defeated_nifl_leader] add no_defeated_nifl_leader
tag @a[tag=defeated_nifl_leader] remove no_defeated_nifl_leader
tag @a[tag=!defeated_nifl_trainer_1] add no_defeated_nifl_trainer_1
tag @a[tag=defeated_nifl_trainer_1] remove no_defeated_nifl_trainer_1
tag @a[tag=!defeated_nifl_trainer_2] add no_defeated_nifl_trainer_2
tag @a[tag=defeated_nifl_trainer_2] remove no_defeated_nifl_trainer_2
tag @a[tag=!defeated_royal_champion] add no_defeated_royal_champion
tag @a[tag=defeated_royal_champion] remove no_defeated_royal_champion
tag @a[tag=!defeated_royal_elite_1] add no_defeated_royal_elite_1
tag @a[tag=defeated_royal_elite_1] remove no_defeated_royal_elite_1
tag @a[tag=!defeated_royal_elite_2] add no_defeated_royal_elite_2
tag @a[tag=defeated_royal_elite_2] remove no_defeated_royal_elite_2
tag @a[tag=!defeated_royal_elite_3] add no_defeated_royal_elite_3
tag @a[tag=defeated_royal_elite_3] remove no_defeated_royal_elite_3
tag @a[tag=!defeated_royal_elite_4] add no_defeated_royal_elite_4
tag @a[tag=defeated_royal_elite_4] remove no_defeated_royal_elite_4
tag @a[tag=!defeated_ryujin_apprentice] add no_defeated_ryujin_apprentice
tag @a[tag=defeated_ryujin_apprentice] remove no_defeated_ryujin_apprentice
tag @a[tag=!defeated_ryujin_leader] add no_defeated_ryujin_leader
tag @a[tag=defeated_ryujin_leader] remove no_defeated_ryujin_leader
tag @a[tag=!defeated_ryujin_trainer_1] add no_defeated_ryujin_trainer_1
tag @a[tag=defeated_ryujin_trainer_1] remove no_defeated_ryujin_trainer_1
tag @a[tag=!defeated_ryujin_trainer_2] add no_defeated_ryujin_trainer_2
tag @a[tag=defeated_ryujin_trainer_2] remove no_defeated_ryujin_trainer_2
tag @a[tag=!defeated_scorchspire_apprentice] add no_defeated_scorchspire_apprentice
tag @a[tag=defeated_scorchspire_apprentice] remove no_defeated_scorchspire_apprentice
tag @a[tag=!defeated_scorchspire_leader] add no_defeated_scorchspire_leader
tag @a[tag=defeated_scorchspire_leader] remove no_defeated_scorchspire_leader
tag @a[tag=!defeated_scorchspire_trainer_1] add no_defeated_scorchspire_trainer_1
tag @a[tag=defeated_scorchspire_trainer_1] remove no_defeated_scorchspire_trainer_1
tag @a[tag=!defeated_scorchspire_trainer_2] add no_defeated_scorchspire_trainer_2
tag @a[tag=defeated_scorchspire_trainer_2] remove no_defeated_scorchspire_trainer_2
tag @a[tag=!defeated_sq_bracket_1] add no_defeated_sq_bracket_1
tag @a[tag=defeated_sq_bracket_1] remove no_defeated_sq_bracket_1
tag @a[tag=!defeated_sq_bracket_2] add no_defeated_sq_bracket_2
tag @a[tag=defeated_sq_bracket_2] remove no_defeated_sq_bracket_2
tag @a[tag=!defeated_sq_bracket_3] add no_defeated_sq_bracket_3
tag @a[tag=defeated_sq_bracket_3] remove no_defeated_sq_bracket_3
tag @a[tag=!defeated_sq_canvasser] add no_defeated_sq_canvasser
tag @a[tag=defeated_sq_canvasser] remove no_defeated_sq_canvasser
tag @a[tag=!defeated_sq_deadletter_agent] add no_defeated_sq_deadletter_agent
tag @a[tag=defeated_sq_deadletter_agent] remove no_defeated_sq_deadletter_agent
tag @a[tag=!defeated_sq_genji_wager] add no_defeated_sq_genji_wager
tag @a[tag=defeated_sq_genji_wager] remove no_defeated_sq_genji_wager
tag @a[tag=!defeated_sq_headcount_wager] add no_defeated_sq_headcount_wager
tag @a[tag=defeated_sq_headcount_wager] remove no_defeated_sq_headcount_wager
tag @a[tag=!defeated_sq_hz_analyst] add no_defeated_sq_hz_analyst
tag @a[tag=defeated_sq_hz_analyst] remove no_defeated_sq_hz_analyst
tag @a[tag=!defeated_sq_kyc_agent] add no_defeated_sq_kyc_agent
tag @a[tag=defeated_sq_kyc_agent] remove no_defeated_sq_kyc_agent
tag @a[tag=!defeated_sq_mayor_suits] add no_defeated_sq_mayor_suits
tag @a[tag=defeated_sq_mayor_suits] remove no_defeated_sq_mayor_suits
tag @a[tag=!defeated_sq_regular_4] add no_defeated_sq_regular_4
tag @a[tag=defeated_sq_regular_4] remove no_defeated_sq_regular_4
tag @a[tag=!defeated_sq_regular_meadow] add no_defeated_sq_regular_meadow
tag @a[tag=defeated_sq_regular_meadow] remove no_defeated_sq_regular_meadow
tag @a[tag=!defeated_sq_regular_spotter] add no_defeated_sq_regular_spotter
tag @a[tag=defeated_sq_regular_spotter] remove no_defeated_sq_regular_spotter
tag @a[tag=!defeated_sq_regular_typetip] add no_defeated_sq_regular_typetip
tag @a[tag=defeated_sq_regular_typetip] remove no_defeated_sq_regular_typetip
tag @a[tag=!defeated_sq_rt2_haoran] add no_defeated_sq_rt2_haoran
tag @a[tag=defeated_sq_rt2_haoran] remove no_defeated_sq_rt2_haoran
tag @a[tag=!defeated_sq_rt2_kite] add no_defeated_sq_rt2_kite
tag @a[tag=defeated_sq_rt2_kite] remove no_defeated_sq_rt2_kite
tag @a[tag=!defeated_sq_rt2_scarecrow] add no_defeated_sq_rt2_scarecrow
tag @a[tag=defeated_sq_rt2_scarecrow] remove no_defeated_sq_rt2_scarecrow
tag @a[tag=!defeated_sq_rt2_wager] add no_defeated_sq_rt2_wager
tag @a[tag=defeated_sq_rt2_wager] remove no_defeated_sq_rt2_wager
tag @a[tag=!defeated_sq_sting_agent] add no_defeated_sq_sting_agent
tag @a[tag=defeated_sq_sting_agent] remove no_defeated_sq_sting_agent
tag @a[tag=!defeated_takehara_apprentice] add no_defeated_takehara_apprentice
tag @a[tag=defeated_takehara_apprentice] remove no_defeated_takehara_apprentice
tag @a[tag=!defeated_takehara_apprentice_weak] add no_defeated_takehara_apprentice_weak
tag @a[tag=defeated_takehara_apprentice_weak] remove no_defeated_takehara_apprentice_weak
tag @a[tag=!defeated_takehara_jr_apprentice] add no_defeated_takehara_jr_apprentice
tag @a[tag=defeated_takehara_jr_apprentice] remove no_defeated_takehara_jr_apprentice
tag @a[tag=!defeated_takehara_jr_apprentice_weak] add no_defeated_takehara_jr_apprentice_weak
tag @a[tag=defeated_takehara_jr_apprentice_weak] remove no_defeated_takehara_jr_apprentice_weak
tag @a[tag=!defeated_takehara_leader] add no_defeated_takehara_leader
tag @a[tag=defeated_takehara_leader] remove no_defeated_takehara_leader
tag @a[tag=!defeated_takehara_leader_weak] add no_defeated_takehara_leader_weak
tag @a[tag=defeated_takehara_leader_weak] remove no_defeated_takehara_leader_weak
tag @a[tag=!defeated_takehara_trainer_1] add no_defeated_takehara_trainer_1
tag @a[tag=defeated_takehara_trainer_1] remove no_defeated_takehara_trainer_1
tag @a[tag=!defeated_takehara_trainer_1_b] add no_defeated_takehara_trainer_1_b
tag @a[tag=defeated_takehara_trainer_1_b] remove no_defeated_takehara_trainer_1_b
tag @a[tag=!defeated_takehara_trainer_2] add no_defeated_takehara_trainer_2
tag @a[tag=defeated_takehara_trainer_2] remove no_defeated_takehara_trainer_2
tag @a[tag=!defeated_takehara_trainer_2_b] add no_defeated_takehara_trainer_2_b
tag @a[tag=defeated_takehara_trainer_2_b] remove no_defeated_takehara_trainer_2_b
tag @a[tag=!defeated_takehara_trainer_3] add no_defeated_takehara_trainer_3
tag @a[tag=defeated_takehara_trainer_3] remove no_defeated_takehara_trainer_3
tag @a[tag=!defeated_takehara_trainer_3_b] add no_defeated_takehara_trainer_3_b
tag @a[tag=defeated_takehara_trainer_3_b] remove no_defeated_takehara_trainer_3_b
tag @a[tag=!defeated_takehara_trainer_4] add no_defeated_takehara_trainer_4
tag @a[tag=defeated_takehara_trainer_4] remove no_defeated_takehara_trainer_4
tag @a[tag=!defeated_takehara_trainer_4_b] add no_defeated_takehara_trainer_4_b
tag @a[tag=defeated_takehara_trainer_4_b] remove no_defeated_takehara_trainer_4_b
tag @a[tag=!defeated_villain_admin] add no_defeated_villain_admin
tag @a[tag=defeated_villain_admin] remove no_defeated_villain_admin
tag @a[tag=!defeated_villain_admin_2] add no_defeated_villain_admin_2
tag @a[tag=defeated_villain_admin_2] remove no_defeated_villain_admin_2
tag @a[tag=!defeated_villain_admin_commander] add no_defeated_villain_admin_commander
tag @a[tag=defeated_villain_admin_commander] remove no_defeated_villain_admin_commander
tag @a[tag=!defeated_villain_boss] add no_defeated_villain_boss
tag @a[tag=defeated_villain_boss] remove no_defeated_villain_boss
tag @a[tag=!defeated_villain_grunt_1] add no_defeated_villain_grunt_1
tag @a[tag=defeated_villain_grunt_1] remove no_defeated_villain_grunt_1
tag @a[tag=!defeated_villain_grunt_10] add no_defeated_villain_grunt_10
tag @a[tag=defeated_villain_grunt_10] remove no_defeated_villain_grunt_10
tag @a[tag=!defeated_villain_grunt_11] add no_defeated_villain_grunt_11
tag @a[tag=defeated_villain_grunt_11] remove no_defeated_villain_grunt_11
tag @a[tag=!defeated_villain_grunt_2] add no_defeated_villain_grunt_2
tag @a[tag=defeated_villain_grunt_2] remove no_defeated_villain_grunt_2
tag @a[tag=!defeated_villain_grunt_3] add no_defeated_villain_grunt_3
tag @a[tag=defeated_villain_grunt_3] remove no_defeated_villain_grunt_3
tag @a[tag=!defeated_villain_grunt_4] add no_defeated_villain_grunt_4
tag @a[tag=defeated_villain_grunt_4] remove no_defeated_villain_grunt_4
tag @a[tag=!defeated_villain_grunt_5] add no_defeated_villain_grunt_5
tag @a[tag=defeated_villain_grunt_5] remove no_defeated_villain_grunt_5
tag @a[tag=!defeated_villain_grunt_6] add no_defeated_villain_grunt_6
tag @a[tag=defeated_villain_grunt_6] remove no_defeated_villain_grunt_6
tag @a[tag=!defeated_villain_grunt_7] add no_defeated_villain_grunt_7
tag @a[tag=defeated_villain_grunt_7] remove no_defeated_villain_grunt_7
tag @a[tag=!defeated_villain_grunt_8] add no_defeated_villain_grunt_8
tag @a[tag=defeated_villain_grunt_8] remove no_defeated_villain_grunt_8
tag @a[tag=!defeated_villain_grunt_9] add no_defeated_villain_grunt_9
tag @a[tag=defeated_villain_grunt_9] remove no_defeated_villain_grunt_9
tag @a[tag=!defeated_villain_route_escort] add no_defeated_villain_route_escort
tag @a[tag=defeated_villain_route_escort] remove no_defeated_villain_route_escort
tag @a[tag=!defeated_villain_route_surveyor] add no_defeated_villain_route_surveyor
tag @a[tag=defeated_villain_route_surveyor] remove no_defeated_villain_route_surveyor
tag @a[tag=!defeated_villain_site_manager] add no_defeated_villain_site_manager
tag @a[tag=defeated_villain_site_manager] remove no_defeated_villain_site_manager
tag @a[tag=!defeated_villain_yield_analyst] add no_defeated_villain_yield_analyst
tag @a[tag=defeated_villain_yield_analyst] remove no_defeated_villain_yield_analyst
tag @a[tag=!defeated_villain_yield_officer] add no_defeated_villain_yield_officer
tag @a[tag=defeated_villain_yield_officer] remove no_defeated_villain_yield_officer
tag @a[tag=!defeated_wheat_trader_ambush] add no_defeated_wheat_trader_ambush
tag @a[tag=defeated_wheat_trader_ambush] remove no_defeated_wheat_trader_ambush
tag @a[tag=!delivered_1] add no_delivered_1
tag @a[tag=delivered_1] remove no_delivered_1
tag @a[tag=!delivered_2] add no_delivered_2
tag @a[tag=delivered_2] remove no_delivered_2
tag @a[tag=!delivered_3] add no_delivered_3
tag @a[tag=delivered_3] remove no_delivered_3
tag @a[tag=!dept_of_two_done] add no_dept_of_two_done
tag @a[tag=dept_of_two_done] remove no_dept_of_two_done
tag @a[tag=!doc_ledger] add no_doc_ledger
tag @a[tag=doc_ledger] remove no_doc_ledger
tag @a[tag=!doc_portrait] add no_doc_portrait
tag @a[tag=doc_portrait] remove no_doc_portrait
tag @a[tag=!docs_filed] add no_docs_filed
tag @a[tag=docs_filed] remove no_docs_filed
tag @a[tag=!errand1_done] add no_errand1_done
tag @a[tag=errand1_done] remove no_errand1_done
tag @a[tag=!errand2_done] add no_errand2_done
tag @a[tag=errand2_done] remove no_errand2_done
tag @a[tag=!errand3_done] add no_errand3_done
tag @a[tag=errand3_done] remove no_errand3_done
tag @a[tag=!farm_1_free] add no_farm_1_free
tag @a[tag=farm_1_free] remove no_farm_1_free
tag @a[tag=!field_memo_filed] add no_field_memo_filed
tag @a[tag=field_memo_filed] remove no_field_memo_filed
tag @a[tag=!file_opened] add no_file_opened
tag @a[tag=file_opened] remove no_file_opened
tag @a[tag=!file_refiled] add no_file_refiled
tag @a[tag=file_refiled] remove no_file_refiled
tag @a[tag=!first_watch_done] add no_first_watch_done
tag @a[tag=first_watch_done] remove no_first_watch_done
tag @a[tag=!genji_rod_done] add no_genji_rod_done
tag @a[tag=genji_rod_done] remove no_genji_rod_done
tag @a[tag=!goodwill_paid] add no_goodwill_paid
tag @a[tag=goodwill_paid] remove no_goodwill_paid
tag @a[tag=!got_pokedex] add no_got_pokedex
tag @a[tag=got_pokedex] remove no_got_pokedex
tag @a[tag=!got_running_shoes] add no_got_running_shoes
tag @a[tag=got_running_shoes] remove no_got_running_shoes
tag @a[tag=!has_firstfurrow_deed] add no_has_firstfurrow_deed
tag @a[tag=has_firstfurrow_deed] remove no_has_firstfurrow_deed
tag @a[tag=!homecoming_paid] add no_homecoming_paid
tag @a[tag=homecoming_paid] remove no_homecoming_paid
tag @a[tag=!hz_minutes_filed] add no_hz_minutes_filed
tag @a[tag=hz_minutes_filed] remove no_hz_minutes_filed
tag @a[tag=!hz_minutes_heard] add no_hz_minutes_heard
tag @a[tag=hz_minutes_heard] remove no_hz_minutes_heard
tag @a[tag=!hz_price_1] add no_hz_price_1
tag @a[tag=hz_price_1] remove no_hz_price_1
tag @a[tag=!hz_price_2] add no_hz_price_2
tag @a[tag=hz_price_2] remove no_hz_price_2
tag @a[tag=!hz_price_3] add no_hz_price_3
tag @a[tag=hz_price_3] remove no_hz_price_3
tag @a[tag=!hz_price_check_active] add no_hz_price_check_active
tag @a[tag=hz_price_check_active] remove no_hz_price_check_active
tag @a[tag=!hz_prices_done] add no_hz_prices_done
tag @a[tag=hz_prices_done] remove no_hz_prices_done
tag @a[tag=!hz_rx_done] add no_hz_rx_done
tag @a[tag=hz_rx_done] remove no_hz_rx_done
tag @a[tag=!hz_survey_active] add no_hz_survey_active
tag @a[tag=hz_survey_active] remove no_hz_survey_active
tag @a[tag=!hz_survey_paid] add no_hz_survey_paid
tag @a[tag=hz_survey_paid] remove no_hz_survey_paid
tag @a[tag=!hz_tour_stamped] add no_hz_tour_stamped
tag @a[tag=hz_tour_stamped] remove no_hz_tour_stamped
tag @a[tag=!id_read_lucian] add no_id_read_lucian
tag @a[tag=id_read_lucian] remove no_id_read_lucian
tag @a[tag=!invit_entered] add no_invit_entered
tag @a[tag=invit_entered] remove no_invit_entered
tag @a[tag=!invit_podium_done] add no_invit_podium_done
tag @a[tag=invit_podium_done] remove no_invit_podium_done
tag @a[tag=!kele_gift] add no_kele_gift
tag @a[tag=kele_gift] remove no_kele_gift
tag @a[tag=!lane_done] add no_lane_done
tag @a[tag=lane_done] remove no_lane_done
tag @a[tag=!lane_started] add no_lane_started
tag @a[tag=lane_started] remove no_lane_started
tag @a[tag=!letter_delivered] add no_letter_delivered
tag @a[tag=letter_delivered] remove no_letter_delivered
tag @a[tag=!manifest_paid] add no_manifest_paid
tag @a[tag=manifest_paid] remove no_manifest_paid
tag @a[tag=!marlow_thanks_done] add no_marlow_thanks_done
tag @a[tag=marlow_thanks_done] remove no_marlow_thanks_done
tag @a[tag=!memo_delivered] add no_memo_delivered
tag @a[tag=memo_delivered] remove no_memo_delivered
tag @a[tag=!memo_heard] add no_memo_heard
tag @a[tag=memo_heard] remove no_memo_heard
tag @a[tag=!notice_1] add no_notice_1
tag @a[tag=notice_1] remove no_notice_1
tag @a[tag=!notice_2] add no_notice_2
tag @a[tag=notice_2] remove no_notice_2
tag @a[tag=!notice_3] add no_notice_3
tag @a[tag=notice_3] remove no_notice_3
tag @a[tag=!notices_filed] add no_notices_filed
tag @a[tag=notices_filed] remove no_notices_filed
tag @a[tag=!nuru_thanks] add no_nuru_thanks
tag @a[tag=nuru_thanks] remove no_nuru_thanks
tag @a[tag=!off_record_blown] add no_off_record_blown
tag @a[tag=off_record_blown] remove no_off_record_blown
tag @a[tag=!off_record_complete] add no_off_record_complete
tag @a[tag=off_record_complete] remove no_off_record_complete
tag @a[tag=!off_record_started] add no_off_record_started
tag @a[tag=off_record_started] remove no_off_record_started
tag @a[tag=!paid_checkpoint_fee] add no_paid_checkpoint_fee
tag @a[tag=paid_checkpoint_fee] remove no_paid_checkpoint_fee
tag @a[tag=!paid_handling_fee] add no_paid_handling_fee
tag @a[tag=paid_handling_fee] remove no_paid_handling_fee
tag @a[tag=!pilgrimage_done] add no_pilgrimage_done
tag @a[tag=pilgrimage_done] remove no_pilgrimage_done
tag @a[tag=!quest_assist_collect_done] add no_quest_assist_collect_done
tag @a[tag=quest_assist_collect_done] remove no_quest_assist_collect_done
tag @a[tag=!quest_assist_mine_done] add no_quest_assist_mine_done
tag @a[tag=quest_assist_mine_done] remove no_quest_assist_mine_done
tag @a[tag=!race_daily_claimed] add no_race_daily_claimed
tag @a[tag=race_daily_claimed] remove no_race_daily_claimed
tag @a[tag=!race_won] add no_race_won
tag @a[tag=race_won] remove no_race_won
tag @a[tag=!royal_league_champion] add no_royal_league_champion
tag @a[tag=royal_league_champion] remove no_royal_league_champion
tag @a[tag=!scrub_report_filed] add no_scrub_report_filed
tag @a[tag=scrub_report_filed] remove no_scrub_report_filed
tag @a[tag=!seal_moss] add no_seal_moss
tag @a[tag=seal_moss] remove no_seal_moss
tag @a[tag=!seal_orchard] add no_seal_orchard
tag @a[tag=seal_orchard] remove no_seal_orchard
tag @a[tag=!seal_pond] add no_seal_pond
tag @a[tag=seal_pond] remove no_seal_pond
tag @a[tag=!seal_terrace] add no_seal_terrace
tag @a[tag=seal_terrace] remove no_seal_terrace
tag @a[tag=!second_starter_claimed] add no_second_starter_claimed
tag @a[tag=second_starter_claimed] remove no_second_starter_claimed
tag @a[tag=!second_starter_unlocked] add no_second_starter_unlocked
tag @a[tag=second_starter_unlocked] remove no_second_starter_unlocked
tag @a[tag=!seen_clean_square] add no_seen_clean_square
tag @a[tag=seen_clean_square] remove no_seen_clean_square
tag @a[tag=!seen_rezoning_notice] add no_seen_rezoning_notice
tag @a[tag=seen_rezoning_notice] remove no_seen_rezoning_notice
tag @a[tag=!sentinel_kit] add no_sentinel_kit
tag @a[tag=sentinel_kit] remove no_sentinel_kit
tag @a[tag=!sold_docs] add no_sold_docs
tag @a[tag=sold_docs] remove no_sold_docs
tag @a[tag=!sq_combee_granted] add no_sq_combee_granted
tag @a[tag=sq_combee_granted] remove no_sq_combee_granted
tag @a[tag=!sq_mayor_roof_done] add no_sq_mayor_roof_done
tag @a[tag=sq_mayor_roof_done] remove no_sq_mayor_roof_done
tag @a[tag=!sq_museum_brush] add no_sq_museum_brush
tag @a[tag=sq_museum_brush] remove no_sq_museum_brush
tag @a[tag=!sq_museum_donation_done] add no_sq_museum_donation_done
tag @a[tag=sq_museum_donation_done] remove no_sq_museum_donation_done
tag @a[tag=!sq_museum_revived] add no_sq_museum_revived
tag @a[tag=sq_museum_revived] remove no_sq_museum_revived
tag @a[tag=!sq_poster_one] add no_sq_poster_one
tag @a[tag=sq_poster_one] remove no_sq_poster_one
tag @a[tag=!sq_poster_scolded] add no_sq_poster_scolded
tag @a[tag=sq_poster_scolded] remove no_sq_poster_scolded
tag @a[tag=!sq_poster_three] add no_sq_poster_three
tag @a[tag=sq_poster_three] remove no_sq_poster_three
tag @a[tag=!sq_poster_two] add no_sq_poster_two
tag @a[tag=sq_poster_two] remove no_sq_poster_two
tag @a[tag=!sq_posters_done] add no_sq_posters_done
tag @a[tag=sq_posters_done] remove no_sq_posters_done
tag @a[tag=!sting_futures_paid] add no_sting_futures_paid
tag @a[tag=sting_futures_paid] remove no_sting_futures_paid
tag @a[tag=!sting_memo_taken] add no_sting_memo_taken
tag @a[tag=sting_memo_taken] remove no_sting_memo_taken
tag @a[tag=!sting_reward_paid] add no_sting_reward_paid
tag @a[tag=sting_reward_paid] remove no_sting_reward_paid
tag @a[tag=!sting_seal_2] add no_sting_seal_2
tag @a[tag=sting_seal_2] remove no_sting_seal_2
tag @a[tag=!sting_seal_3] add no_sting_seal_3
tag @a[tag=sting_seal_3] remove no_sting_seal_3
tag @a[tag=!sting_seal_4] add no_sting_seal_4
tag @a[tag=sting_seal_4] remove no_sting_seal_4
tag @a[tag=!sting_seal_4_clear] add no_sting_seal_4_clear
tag @a[tag=sting_seal_4_clear] remove no_sting_seal_4_clear
tag @a[tag=!supper_delivered] add no_supper_delivered
tag @a[tag=supper_delivered] remove no_supper_delivered
tag @a[tag=!supper_taken] add no_supper_taken
tag @a[tag=supper_taken] remove no_supper_taken
tag @a[tag=!survey_done] add no_survey_done
tag @a[tag=survey_done] remove no_survey_done
tag @a[tag=!third_starter_claimed] add no_third_starter_claimed
tag @a[tag=third_starter_claimed] remove no_third_starter_claimed
tag @a[tag=!third_starter_unlocked] add no_third_starter_unlocked
tag @a[tag=third_starter_unlocked] remove no_third_starter_unlocked
tag @a[tag=!took_route_manifest] add no_took_route_manifest
tag @a[tag=took_route_manifest] remove no_took_route_manifest
tag @a[tag=!traded_sefu] add no_traded_sefu
tag @a[tag=traded_sefu] remove no_traded_sefu
tag @a[tag=!transition_paid] add no_transition_paid
tag @a[tag=transition_paid] remove no_transition_paid
tag @a[tag=!verification_bonus_paid] add no_verification_bonus_paid
tag @a[tag=verification_bonus_paid] remove no_verification_bonus_paid
tag @a[tag=!wheat_named] add no_wheat_named
tag @a[tag=wheat_named] remove no_wheat_named
tag @a[tag=!work_all_done] add no_work_all_done
tag @a[tag=work_all_done] remove no_work_all_done
tag @a[tag=!work_fetch_done] add no_work_fetch_done
tag @a[tag=work_fetch_done] remove no_work_fetch_done
tag @a[tag=!work_mine_done] add no_work_mine_done
tag @a[tag=work_mine_done] remove no_work_mine_done
tag @a[tag=!work_night_done] add no_work_night_done
tag @a[tag=work_night_done] remove no_work_night_done
tag @a[tag=!work_night_paid] add no_work_night_paid
tag @a[tag=work_night_paid] remove no_work_night_paid
tag @a[tag=!yield_report_taken] add no_yield_report_taken
tag @a[tag=yield_report_taken] remove no_yield_report_taken

