# register_sight — NPC Sight registrations for dialog-src NPCs.
# Auto-generated by scripts/content_compile. Run AFTER update_npc_presets.
# /function cobblemon_initiative:dialog/register_sight   (OP level 2)

# Nalia (nalia_mom)
npcsight add 74b1c524-0c3c-4a19-943d-f6f05c0e7f94 5 default
npcsight mode 74b1c524-0c3c-4a19-943d-f6f05c0e7f94 approach_once
npcsight meettag 74b1c524-0c3c-4a19-943d-f6f05c0e7f94 met_mom
