# register_sight — NPC Sight registrations for dialog-src NPCs.
# Auto-generated by scripts/content_compile. Run AFTER update_npc_presets.
# /function cobblemon_initiative:dialog/register_sight   (OP level 2)

# Bo (hz_greenhouse_greeter)
npcsight add a9bebc53-64b7-4466-a08c-84101ab9809a 6 welcome
npcsight mode a9bebc53-64b7-4466-a08c-84101ab9809a approach_once
npcsight meettag a9bebc53-64b7-4466-a08c-84101ab9809a met_hz_greeter
# Zola (sq_regular_4)
npcsight add 4db98c02-4445-4162-a2ac-a80c4cd4f685 8
npcsight mode 4db98c02-4445-4162-a2ac-a80c4cd4f685 pursue
npcsight stoptag 4db98c02-4445-4162-a2ac-a80c4cd4f685 defeated_sq_regular_4
# Jabari (sq_regular_meadow)
npcsight add dfd6ef2c-028e-403c-ac0e-3e77149fea30 8
npcsight mode dfd6ef2c-028e-403c-ac0e-3e77149fea30 pursue
npcsight stoptag dfd6ef2c-028e-403c-ac0e-3e77149fea30 defeated_sq_regular_meadow
# Bird Keeper Ayo (sq_regular_spotter)
npcsight add 4637e716-e0e0-48f0-9359-c9c2292574c5 8
npcsight mode 4637e716-e0e0-48f0-9359-c9c2292574c5 pursue
npcsight stoptag 4637e716-e0e0-48f0-9359-c9c2292574c5 defeated_sq_regular_spotter
# Bird Keeper Kwame (sq_regular_typetip)
npcsight add 932ba1f1-fd1f-4ea4-837f-dcc16bf0bf4b 8
npcsight mode 932ba1f1-fd1f-4ea4-837f-dcc16bf0bf4b pursue
npcsight stoptag 932ba1f1-fd1f-4ea4-837f-dcc16bf0bf4b defeated_sq_regular_typetip
# Azim Kadar (azim_kadar)
npcsight add bae5a580-e1d1-4796-8465-688c57105e69 9
npcsight mode bae5a580-e1d1-4796-8465-688c57105e69 pursue
npcsight stoptag bae5a580-e1d1-4796-8465-688c57105e69 defeated_azim_kadar
# Nadir Khemet (nadir_khemet)
npcsight add 425394be-5d28-4dc9-bce7-8b7390fb805a 9
npcsight mode 425394be-5d28-4dc9-bce7-8b7390fb805a pursue
npcsight stoptag 425394be-5d28-4dc9-bce7-8b7390fb805a defeated_nadir_khemet
# Rashid Anwar (rashid_anwar)
npcsight add d939ab8b-4cec-47fd-9016-389e4da7422a 9
npcsight mode d939ab8b-4cec-47fd-9016-389e4da7422a pursue
npcsight stoptag d939ab8b-4cec-47fd-9016-389e4da7422a defeated_rashid_anwar
# Soraya Neith (soraya_neith)
npcsight add bd96b93e-66b7-4e18-97ff-384289bd2a0a 9
npcsight mode bd96b93e-66b7-4e18-97ff-384289bd2a0a pursue
npcsight stoptag bd96b93e-66b7-4e18-97ff-384289bd2a0a defeated_soraya_neith
# Axel Datastream (axel_datastream)
npcsight add fc3c747f-801e-4685-a25c-f38faa754361 9
npcsight mode fc3c747f-801e-4685-a25c-f38faa754361 pursue
npcsight stoptag fc3c747f-801e-4685-a25c-f38faa754361 defeated_axel_datastream
# Byte Razer (byte_razer)
npcsight add 69dc379e-4050-45aa-b2cf-5deac79cb508 9
npcsight mode 69dc379e-4050-45aa-b2cf-5deac79cb508 pursue
npcsight stoptag 69dc379e-4050-45aa-b2cf-5deac79cb508 defeated_byte_razer
# Arden Drakepath (r13_sight_arden)
npcsight add 91a45654-86dc-4c71-b325-5ed33013ebb3 9
npcsight mode 91a45654-86dc-4c71-b325-5ed33013ebb3 pursue
npcsight stoptag 91a45654-86dc-4c71-b325-5ed33013ebb3 defeated_r13_sight_arden
# Korin Flameclaw (r13_sight_korin)
npcsight add e1c2098c-d156-434f-85d0-558f9865364d 9
npcsight mode e1c2098c-d156-434f-85d0-558f9865364d pursue
npcsight stoptag e1c2098c-d156-434f-85d0-558f9865364d defeated_r13_sight_korin
# Lyra Stormflight (r13_sight_lyra)
npcsight add 9e4f8f49-7583-4362-b673-58cd0853a263 9
npcsight mode 9e4f8f49-7583-4362-b673-58cd0853a263 pursue
npcsight stoptag 9e4f8f49-7583-4362-b673-58cd0853a263 defeated_r13_sight_lyra
# Brynja Frostarrow (r14_sight_brynja)
npcsight add fa0d3d49-8798-44ed-a1ed-237ff091903a 9
npcsight mode fa0d3d49-8798-44ed-a1ed-237ff091903a pursue
npcsight stoptag fa0d3d49-8798-44ed-a1ed-237ff091903a defeated_r14_sight_brynja
# Sten Glacierguard (r14_sight_sten)
npcsight add f1c46091-a3bc-4626-89ae-c239ad43eb5f 9
npcsight mode f1c46091-a3bc-4626-89ae-c239ad43eb5f pursue
npcsight stoptag f1c46091-a3bc-4626-89ae-c239ad43eb5f defeated_r14_sight_sten
# Torvald Snowrunner (r14_sight_torvald)
npcsight add 44443ff7-d8e9-4dcb-875d-5c3477882b16 9
npcsight mode 44443ff7-d8e9-4dcb-875d-5c3477882b16 pursue
npcsight stoptag 44443ff7-d8e9-4dcb-875d-5c3477882b16 defeated_r14_sight_torvald
# Cassia Stormrider (r16_sight_cassia)
npcsight add 8a68b2fa-4cad-41f0-b8dc-c8e4bf826099 9
npcsight mode 8a68b2fa-4cad-41f0-b8dc-c8e4bf826099 pursue
npcsight stoptag 8a68b2fa-4cad-41f0-b8dc-c8e4bf826099 defeated_r16_sight_cassia
# Drake Ironclaw (r16_sight_drake)
npcsight add 9a10dff9-8188-4811-89e0-67529cf652ec 9
npcsight mode 9a10dff9-8188-4811-89e0-67529cf652ec pursue
npcsight stoptag 9a10dff9-8188-4811-89e0-67529cf652ec defeated_r16_sight_drake
# Lysandra Skyflare (r16_sight_lysandra)
npcsight add b28a9a27-1436-4924-b1d1-e7bf1f4a35ba 9
npcsight mode b28a9a27-1436-4924-b1d1-e7bf1f4a35ba pursue
npcsight stoptag b28a9a27-1436-4924-b1d1-e7bf1f4a35ba defeated_r16_sight_lysandra
# Ronan Peakguard (r16_sight_ronan)
npcsight add 984108b8-bc5e-414f-af6a-d7927334fb50 9
npcsight mode 984108b8-bc5e-414f-af6a-d7927334fb50 pursue
npcsight stoptag 984108b8-bc5e-414f-af6a-d7927334fb50 defeated_r16_sight_ronan
# Sporeherd Maslen (mirek)
npcsight add ae9aa285-8251-46db-a520-ab00dab02a21 8
npcsight mode ae9aa285-8251-46db-a520-ab00dab02a21 pursue
npcsight stoptag ae9aa285-8251-46db-a520-ab00dab02a21 defeated_r3_trainer_shroom
# Kite Runner Xu Jianyu (xu_jianyu)
npcsight add 535c306c-cb90-43c1-a405-e84099a01b8d 8
npcsight mode 535c306c-cb90-43c1-a405-e84099a01b8d pursue
npcsight stoptag 535c306c-cb90-43c1-a405-e84099a01b8d defeated_sq_rt2_kite
# Rowan (rowan)
npcsight add 1f5eaff3-56c0-4b4f-bca5-ec2e49d93660 8
npcsight mode 1f5eaff3-56c0-4b4f-bca5-ec2e49d93660 pursue
npcsight stoptag 1f5eaff3-56c0-4b4f-bca5-ec2e49d93660 defeated_r3_trainer_rowan
# Selene (selene)
npcsight add 19625595-ee88-4ab8-a671-b7e3e8fdac01 8
npcsight mode 19625595-ee88-4ab8-a671-b7e3e8fdac01 pursue
npcsight stoptag 19625595-ee88-4ab8-a671-b7e3e8fdac01 defeated_r3_trainer_selene
# Darrik Stonevein (darrik_stonevein)
npcsight add efb0b45f-6069-478b-9cca-dc82ed9973e7 8
npcsight mode efb0b45f-6069-478b-9cca-dc82ed9973e7 pursue
npcsight stoptag efb0b45f-6069-478b-9cca-dc82ed9973e7 defeated_r5_trainer_darrik
# Helda Ironstep (helda_ironstep)
npcsight add 15a61002-e396-457d-99ae-d4f8c52f8eef 8
npcsight mode 15a61002-e396-457d-99ae-d4f8c52f8eef pursue
npcsight stoptag 15a61002-e396-457d-99ae-d4f8c52f8eef defeated_r5_trainer_helda
# Kelda Deepmark (kelda_deepmark)
npcsight add 15f6a57e-a7a3-4e2b-80f3-d58e4745a811 8
npcsight mode 15f6a57e-a7a3-4e2b-80f3-d58e4745a811 pursue
npcsight stoptag 15f6a57e-a7a3-4e2b-80f3-d58e4745a811 defeated_r5_trainer_kelda
# Rovan Pickstride (rovan_pickstride)
npcsight add 4b74f60b-5fb3-45b8-a318-c9a89c6f1a84 8
npcsight mode 4b74f60b-5fb3-45b8-a318-c9a89c6f1a84 pursue
npcsight stoptag 4b74f60b-5fb3-45b8-a318-c9a89c6f1a84 defeated_r5_trainer_rovan
# Drakar Cinderstrike (cinderfall_drakar)
npcsight add 41a813d2-07c4-46bd-8542-fd12fc22955d 9
npcsight mode 41a813d2-07c4-46bd-8542-fd12fc22955d pursue
npcsight stoptag 41a813d2-07c4-46bd-8542-fd12fc22955d defeated_cinderfall_drakar
# Ignar Lavawalker (cinderfall_ignar)
npcsight add 58576450-2938-4482-a572-db66c5ba53be 9
npcsight mode 58576450-2938-4482-a572-db66c5ba53be pursue
npcsight stoptag 58576450-2938-4482-a572-db66c5ba53be defeated_cinderfall_ignar
# Karn Pyroclast (cinderfall_karn)
npcsight add fcc3b66a-edf4-4fcf-95a1-04fb247dac3f 9
npcsight mode fcc3b66a-edf4-4fcf-95a1-04fb247dac3f pursue
npcsight stoptag fcc3b66a-edf4-4fcf-95a1-04fb247dac3f defeated_cinderfall_karn
# Vexa Ashclaw (cinderfall_vexa)
npcsight add 7b37657a-ed61-4ffc-a32e-29056cd9b397 9
npcsight mode 7b37657a-ed61-4ffc-a32e-29056cd9b397 pursue
npcsight stoptag 7b37657a-ed61-4ffc-a32e-29056cd9b397 defeated_cinderfall_vexa
# Lucian Scrollkeeper (lucian_scrollkeeper)
npcsight add 7aeca5b3-1f72-4072-a8c4-e6eef877f160 6 open_file
npcsight mode 7aeca5b3-1f72-4072-a8c4-e6eef877f160 approach_once
npcsight meettag 7aeca5b3-1f72-4072-a8c4-e6eef877f160 met_lucian
# Nalia (nalia_mom)
npcsight add 74b1c524-0c3c-4a19-943d-f6f05c0e7f94 12 default
npcsight mode 74b1c524-0c3c-4a19-943d-f6f05c0e7f94 approach_once
npcsight meettag 74b1c524-0c3c-4a19-943d-f6f05c0e7f94 met_mom
npcsight stoptag 74b1c524-0c3c-4a19-943d-f6f05c0e7f94 met_mom
# Kazuo (company_canvasser)
npcsight add 77d7fb8d-a289-4b8c-a275-1333dd3226d8 10
npcsight mode 77d7fb8d-a289-4b8c-a275-1333dd3226d8 dialog
