# register_sight — NPC Sight registrations for dialog-src NPCs.
# Auto-generated by scripts/content_compile. Run AFTER update_npc_presets.
# /function cobblemon_initiative:dialog/register_sight   (OP level 2)

# Lucian Scrollkeeper (lucian_scrollkeeper)
npcsight add bdc36dd5-29ad-4d14-87d4-44ffa3f609e2 6 open_file
npcsight mode bdc36dd5-29ad-4d14-87d4-44ffa3f609e2 approach_once
npcsight meettag bdc36dd5-29ad-4d14-87d4-44ffa3f609e2 met_lucian
# Nalia (nalia_mom)
npcsight add 74b1c524-0c3c-4a19-943d-f6f05c0e7f94 5 default
npcsight mode 74b1c524-0c3c-4a19-943d-f6f05c0e7f94 approach_once
npcsight meettag 74b1c524-0c3c-4a19-943d-f6f05c0e7f94 met_mom
