# reveal/apply_stage_1 — re-import the Founder at reveal stage 1/4.
# Auto-generated by scripts/generate_founder_reveals — do not hand-edit.
# Fired by reveal/board_fell when the matching number of Board members has fallen.
#
# (no Founder NPC recorded yet — place them, map the UUID to preset
#  "villain_final_boss" in npc_presets.json, then re-run
#  scripts/generate_founder_reveals to fill these functions in)
