# granary/apply_post_hq — retier every Granary NPC to the post_hq trade preset.
# Auto-generated by scripts/generate_granary_tiers — do not hand-edit.
# Fired by ShopTierManager after the matching CobbleDollars shop tier swap
# (or manually: /function cobblemon_initiative:granary/apply_post_hq).

# Feng (skipped when not loaded)
execute as e9c7b916-9b03-417b-808a-10cc4439148b at @s run easy_npc preset import data easy_npc:preset/humanoid/granary_keeper_post_hq.npc.snbt ~ ~ ~ e9c7b916-9b03-417b-808a-10cc4439148b
