# granary/apply_badge_3 — retier every Granary NPC to the badge_3 trade preset.
# Auto-generated by scripts/generate_granary_tiers — do not hand-edit.
# Fired by ShopTierManager after the matching CobbleDollars shop tier swap
# (or manually: /function cobblemon_initiative:granary/apply_badge_3).

# Granary Keeper
easy_npc preset import data e9c7b916-9b03-417b-808a-10cc4439148b cobblemon_initiative:humanoid/granary_keeper_badge_3
