# granary/apply_post_hq_relief1 — retier every Granary NPC to the post_hq_relief1 trade preset.
# Auto-generated by scripts/generate_granary_tiers — do not hand-edit.
# Fired by ShopTierManager after the matching CobbleDollars shop tier swap
# (or manually: /function cobblemon_initiative:granary/apply_post_hq_relief1).
#
# (no Granary NPCs recorded yet — place one, map its UUID to preset
#  "humanoid/granary_keeper" in npc_presets.json, then re-run
#  scripts/generate_granary_tiers to fill these functions in)
