# granary/apply_badge_1 — retier every Granary NPC to the badge_1 trade preset.
# Auto-generated by scripts/generate_granary_tiers — do not hand-edit.
# Fired by ShopTierManager after the matching CobbleDollars shop tier swap
# (or manually: /function cobblemon_initiative:granary/apply_badge_1).

# Granary Keeper
easy_npc preset import data cobblemon_initiative:humanoid/granary_keeper_badge_1 e9c7b916-9b03-417b-808a-10cc4439148b
