# decline_sq_rt2_wager — pay 60 CD to bow out of Harvest Hand Luo Shiming.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 60 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_sq_rt2_wager (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_sq_rt2_wager] unless entity @s[tag=defeated_sq_rt2_wager] store result score #decl_ok cd_calc run cobbledollars pay @s 60
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 60
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_sq_rt2_wager
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 60 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_sq_rt2_wager] unless entity @s[tag=defeated_sq_rt2_wager] run tbcs battle GEN_9_SINGLES @s vs rctmod:sq_rt2_wager onwin {1: ['cobbledollars give @1 380', 'tag @1 add defeated_sq_rt2_wager', '@2 say Doubled the wrong way. Take the stake — it was won fair, which is more than my pay can say.', 'execute as @1 run function cobblemon_initiative:economy/wager_sweetener'], 2: ['cobbledollars remove @2 120', '@1 say The stake stays with the crew. It buys a real dinner tonight, so no hard feelings.']}
