# decline_sq_regular_spotter — pay 100 CD to bow out of Bird Keeper Ayo.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 100 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_sq_regular_spotter (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_sq_regular_spotter] unless entity @s[tag=defeated_sq_regular_spotter] store result score #decl_ok cd_calc run cobbledollars pay @s 100
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 100
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_sq_regular_spotter
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 100 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_sq_regular_spotter] unless entity @s[tag=defeated_sq_regular_spotter] run tbcs battle GEN_9_SINGLES @s vs rctmod:sq_regular_spotter onwin {1: ['cobbledollars give @1 200', 'tag @1 add defeated_sq_regular_spotter', '@2 say Sharp. My eyes are good but your team is better.'], 2: ['@1 say I saw that coming. Literally. It is my whole thing.']}
