# decline_r5_trainer_kelda — pay 200 CD to bow out of Kelda Deepmark.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 200 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_r5_trainer_kelda (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_r5_trainer_kelda] unless entity @s[tag=defeated_r5_trainer_kelda] store result score #decl_ok cd_calc run cobbledollars pay @s 200
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 200
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_r5_trainer_kelda
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 200 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_r5_trainer_kelda] unless entity @s[tag=defeated_r5_trainer_kelda] run tbcs battle GEN_9_SINGLES @s vs rctmod:r5_trainer_kelda onwin {1: ['cobbledollars give @1 420', 'tag @1 add defeated_r5_trainer_kelda', '@2 say Full depth reached. The rim is open — Deepcore will know the road sent you.', 'tag @1 remove in_trainer_battle'], 2: ['@1 say Shallow mark. Climb back down, train, and reach for full depth again.', 'tag @2 remove in_trainer_battle']}
