# decline_soraya_neith — pay 320 CD to bow out of Soraya Neith.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 320 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_soraya_neith (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_soraya_neith] unless entity @s[tag=defeated_soraya_neith] store result score #decl_ok cd_calc run cobbledollars pay @s 320
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 320
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_soraya_neith
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 320 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_soraya_neith] unless entity @s[tag=defeated_soraya_neith] run tbcs battle GEN_9_SINGLES @s vs rctmod:soraya_neith onwin {1: ['cobbledollars give @1 650', 'tag @1 add defeated_soraya_neith', '@2 say The gate remembers you kindly. Walk on before the light goes.', 'tag @1 remove in_trainer_battle'], 2: ['@1 say The ruin keeps its quiet. Come back louder.', 'tag @2 remove in_trainer_battle']}
