# decline_r3_trainer_shroom — pay 160 CD to bow out of Sporeherd Maslen.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 160 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_r3_trainer_shroom (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_r3_trainer_shroom] unless entity @s[tag=defeated_r3_trainer_shroom] store result score #decl_ok cd_calc run cobbledollars pay @s 160
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 160
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_r3_trainer_shroom
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 160 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_r3_trainer_shroom] unless entity @s[tag=defeated_r3_trainer_shroom] run tbcs battle GEN_9_SINGLES @s vs rctmod:r3_trainer_shroom onwin {1: ['cobbledollars give @1 340', 'tag @1 add defeated_r3_trainer_shroom', '@2 say Well grown. You root deeper than you look. The road past the hollow is yours.', 'tag @1 remove in_trainer_battle'], 2: ['@1 say The damp wins by waiting. Dry off, rest your team, and come back to the hollow.', 'tag @2 remove in_trainer_battle']}
