# decline_villain_yield_analyst — pay 150 CD to bow out of Yan.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 150 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_villain_yield_analyst (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_villain_yield_analyst] unless entity @s[tag=defeated_villain_yield_analyst] store result score #decl_ok cd_calc run cobbledollars pay @s 150
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 150
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_villain_yield_analyst
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 150 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_villain_yield_analyst] unless entity @s[tag=defeated_villain_yield_analyst] run tbcs battle GEN_9_SINGLES @s vs rctmod:villain_yield_analyst onwin {1: ['cobbledollars give @1 480', 'tag @1 add defeated_villain_yield_analyst', '@2 say Recorded. One loss, assessor. My confidence interval did not include you — which is itself a data point.'], 2: ['@1 say Engagement concluded. Your challenge has been logged as community sentiment, weight zero.']}
