# decline_ryujin_heritage_envoy — pay 400 CD to bow out of Heritage Acquisitions Envoy.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 400 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_ryujin_heritage_envoy (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_ryujin_heritage_envoy] unless entity @s[tag=defeated_ryujin_heritage_envoy] store result score #decl_ok cd_calc run cobbledollars pay @s 400
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 400
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_ryujin_heritage_envoy
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 400 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_ryujin_heritage_envoy] unless entity @s[tag=defeated_ryujin_heritage_envoy] run tbcs battle GEN_9_SINGLES @s vs rctmod:ryujin_heritage_envoy onwin {1: ['cobbledollars give @1 1200', 'tag @1 add defeated_ryujin_heritage_envoy', '@2 say Acquisition failed. The asset is - hostile. I am revising the valuation and the northern portfolio both. This was never sanctioned by anyone whose name I can still say.', 'tag @1 add ryujin_heritage_settled'], 2: ['@1 say The Company thanks the keep for its cooperation. Heritage class. Retained. As it was always going to be.']}
