# decline_azim_kadar — pay 350 CD to bow out of Azim Kadar.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 350 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_azim_kadar (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_azim_kadar] unless entity @s[tag=defeated_azim_kadar] store result score #decl_ok cd_calc run cobbledollars pay @s 350
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 350
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_azim_kadar
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 350 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_azim_kadar] unless entity @s[tag=defeated_azim_kadar] run tbcs battle GEN_9_SINGLES @s vs rctmod:azim_kadar onwin {1: ['cobbledollars give @1 700', 'tag @1 add defeated_azim_kadar', '@2 say You will do fine under the wires. Give the neon my regards - and nothing else.', 'tag @1 remove in_trainer_battle'], 2: ['@1 say The rise holds you. The desert is kinder than what is past it - train here first.', 'tag @2 remove in_trainer_battle']}
