# decline_layla_zahira — pay 320 CD to bow out of Layla Zahira.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 320 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_layla_zahira (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_layla_zahira] unless entity @s[tag=defeated_layla_zahira] store result score #decl_ok cd_calc run cobbledollars pay @s 320
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 320
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_layla_zahira
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 320 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_layla_zahira] unless entity @s[tag=defeated_layla_zahira] run tbcs battle GEN_9_SINGLES @s vs rctmod:layla_zahira onwin {1: ['cobbledollars give @1 700', 'tag @1 add defeated_layla_zahira', '@2 say You cut clean through the mirage. Few do. The gate is yours - Gaias waits.', 'tag @1 remove in_trainer_battle'], 2: ['@1 say The mirage keeps the unready. Sharpen up and find me again.', 'tag @2 remove in_trainer_battle']}
