# decline_r13_trainer_spine — pay 380 CD to bow out of Dragonrider Kaen.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 380 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_r13_trainer_spine (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_r13_trainer_spine] unless entity @s[tag=defeated_r13_trainer_spine] store result score #decl_ok cd_calc run cobbledollars pay @s 380
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 380
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_r13_trainer_spine
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 380 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_r13_trainer_spine] unless entity @s[tag=defeated_r13_trainer_spine] run tbcs battle GEN_9_SINGLES @s vs rctmod:r13_trainer_spine onwin {1: ['cobbledollars give @1 850', 'tag @1 add defeated_r13_trainer_spine', '@2 say Solid seat. You ride the thin air like you were born to the ridge. Ryujin will respect that.'], 2: ['@1 say The spine humbles every rider once. Rest at the waypost and climb again.']}
