# decline_sq_ryujin_tetsu_wager — pay 200 CD to bow out of Dragonsmith Tetsu.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 200 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_sq_ryujin_tetsu_wager (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_sq_ryujin_tetsu_wager] unless entity @s[tag=defeated_sq_ryujin_tetsu_wager] store result score #decl_ok cd_calc run cobbledollars pay @s 200
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 200
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_sq_ryujin_tetsu_wager
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 200 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_sq_ryujin_tetsu_wager] unless entity @s[tag=defeated_sq_ryujin_tetsu_wager] run tbcs battle GEN_9_SINGLES @s vs rctmod:sq_ryujin_tetsu_wager onwin {1: ['cobbledollars give @1 700', 'tag @1 add defeated_sq_ryujin_tetsu_wager', '@2 say Ha. The forge respects a hot hand. Seven hundred, and no shame in the losing - a dragon that never loses never learns to bite.', 'execute as @1 run function cobblemon_initiative:economy/wager_sweetener'], 2: ['cobbledollars remove @2 700', '@1 say The stake stays on the anvil. Call it tuition. My old wyrms have thrown better climbers than you off this spire, and none of them held it against me either.']}
