# decline_r5_trainer_darrik — pay 190 CD to bow out of Darrik Stonevein.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 190 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_r5_trainer_darrik (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_r5_trainer_darrik] unless entity @s[tag=defeated_r5_trainer_darrik] store result score #decl_ok cd_calc run cobbledollars pay @s 190
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 190
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_r5_trainer_darrik
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 190 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_r5_trainer_darrik] unless entity @s[tag=defeated_r5_trainer_darrik] run tbcs battle GEN_9_SINGLES @s vs rctmod:r5_trainer_darrik onwin {1: ['cobbledollars give @1 400', 'tag @1 add defeated_r5_trainer_darrik', '@2 say There. The hum settles. You are true ore, not seam waste.', 'tag @1 remove in_trainer_battle'], 2: ['@1 say The stone pressed back harder. Rest and return — the vein is patient.', 'tag @2 remove in_trainer_battle']}
