# decline_r14_sight_brynja — pay 450 CD to bow out of Brynja Frostarrow.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 450 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_r14_sight_brynja (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_r14_sight_brynja] unless entity @s[tag=defeated_r14_sight_brynja] store result score #decl_ok cd_calc run cobbledollars pay @s 450
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 450
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_r14_sight_brynja
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 450 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_r14_sight_brynja] unless entity @s[tag=defeated_r14_sight_brynja] run tbcs battle GEN_9_SINGLES @s vs rctmod:r14_sight_brynja onwin {1: ['cobbledollars give @1 900', 'tag @1 add defeated_r14_sight_brynja', '@2 say A true aim answers a true aim. The tarn is open - Nifl is one ridge on.', 'tag @1 remove in_trainer_battle'], 2: ['@1 say You blinked on my ice. Steady your aim and range the tarn again.', 'tag @2 remove in_trainer_battle']}
