# decline_r13_sight_arden — pay 390 CD to bow out of Arden Drakepath.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 390 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_r13_sight_arden (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_r13_sight_arden] unless entity @s[tag=defeated_r13_sight_arden] store result score #decl_ok cd_calc run cobbledollars pay @s 390
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 390
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_r13_sight_arden
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 390 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_r13_sight_arden] unless entity @s[tag=defeated_r13_sight_arden] run tbcs battle GEN_9_SINGLES @s vs rctmod:r13_sight_arden onwin {1: ['cobbledollars give @1 780', 'tag @1 add defeated_r13_sight_arden', '@2 say Clean line up the ridge. The switchbacks are yours - Ryujin waits above.', 'tag @1 remove in_trainer_battle'], 2: ['@1 say The thin air took your legs. Rest at the rail and climb again.', 'tag @2 remove in_trainer_battle']}
