# decline_r14_sight_sten — pay 470 CD to bow out of Sten Glacierguard.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 470 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_r14_sight_sten (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_r14_sight_sten] unless entity @s[tag=defeated_r14_sight_sten] store result score #decl_ok cd_calc run cobbledollars pay @s 470
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 470
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_r14_sight_sten
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 470 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_r14_sight_sten] unless entity @s[tag=defeated_r14_sight_sten] run tbcs battle GEN_9_SINGLES @s vs rctmod:r14_sight_sten onwin {1: ['cobbledollars give @1 940', 'tag @1 add defeated_r14_sight_sten', '@2 say You held the cold and your ground. The glacier gate is open - the Ice leader is up the steps.', 'tag @1 remove in_trainer_battle'], 2: ['@1 say The freeze took you at the gate. Thaw out and hold the line again.', 'tag @2 remove in_trainer_battle']}
