# decline_r16_sight_cassia — pay 500 CD to bow out of Cassia Stormrider.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 500 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_r16_sight_cassia (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_r16_sight_cassia] unless entity @s[tag=defeated_r16_sight_cassia] store result score #decl_ok cd_calc run cobbledollars pay @s 500
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 500
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_r16_sight_cassia
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 500 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_r16_sight_cassia] unless entity @s[tag=defeated_r16_sight_cassia] run tbcs battle GEN_9_SINGLES @s vs rctmod:r16_sight_cassia onwin {1: ['cobbledollars give @1 1000', 'tag @1 add defeated_r16_sight_cassia', '@2 say You crossed the wind without flinching. The bridge is yours - the summit is closer.', 'tag @1 remove in_trainer_battle'], 2: ['@1 say The wind bridge took your nerve. Steady up and cross again.', 'tag @2 remove in_trainer_battle']}
