# decline_zahra_qadir — pay 290 CD to bow out of Zahra Qadir.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 290 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_zahra_qadir (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_zahra_qadir] unless entity @s[tag=defeated_zahra_qadir] store result score #decl_ok cd_calc run cobbledollars pay @s 290
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 290
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_zahra_qadir
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 290 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_zahra_qadir] unless entity @s[tag=defeated_zahra_qadir] run tbcs battle GEN_9_SINGLES @s vs rctmod:zahra_qadir onwin {1: ['cobbledollars give @1 600', 'tag @1 add defeated_zahra_qadir', '@2 say Well fought. The brine is yours to cross. Kalahar water is worse than none.', 'tag @1 remove in_trainer_battle'], 2: ['@1 say The pool takes the tired. Rest and come back to it.', 'tag @2 remove in_trainer_battle']}
