# decline_r7_trainer_lino — pay 240 CD to bow out of Lino Passavento.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 240 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_r7_trainer_lino (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_r7_trainer_lino] unless entity @s[tag=defeated_r7_trainer_lino] store result score #decl_ok cd_calc run cobbledollars pay @s 240
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 240
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_r7_trainer_lino
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 240 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_r7_trainer_lino] unless entity @s[tag=defeated_r7_trainer_lino] run tbcs battle GEN_9_SINGLES @s vs rctmod:r7_trainer_lino onwin {1: ['cobbledollars give @1 500', 'tag @1 add defeated_r7_trainer_lino', '@2 say Solid. You go through rock the way water does. The road is open.', 'tag @1 remove in_trainer_battle'], 2: ['@1 say The quarry taught me patience. Come back when you have learned some.', 'tag @2 remove in_trainer_battle']}
