# decline_r5_trainer_helda — pay 190 CD to bow out of Helda Ironstep.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 190 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_r5_trainer_helda (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_r5_trainer_helda] unless entity @s[tag=defeated_r5_trainer_helda] store result score #decl_ok cd_calc run cobbledollars pay @s 190
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 190
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_r5_trainer_helda
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 190 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_r5_trainer_helda] unless entity @s[tag=defeated_r5_trainer_helda] run tbcs battle GEN_9_SINGLES @s vs rctmod:r5_trainer_helda onwin {1: ['cobbledollars give @1 400', 'tag @1 add defeated_r5_trainer_helda', '@2 say Weighed and passed. My cart tips its rail to you.', 'tag @1 remove in_trainer_battle'], 2: ['@1 say Too light. Feed your team, train your back, come back heavier.', 'tag @2 remove in_trainer_battle']}
