# decline_sq_hz_analyst — pay 80 CD to bow out of Lan.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 80 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_sq_hz_analyst (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_sq_hz_analyst] unless entity @s[tag=defeated_sq_hz_analyst] store result score #decl_ok cd_calc run cobbledollars pay @s 80
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 80
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_sq_hz_analyst
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 80 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_sq_hz_analyst] unless entity @s[tag=defeated_sq_hz_analyst] run tbcs battle GEN_9_SINGLES @s vs rctmod:sq_hz_analyst onwin {1: ['cobbledollars give @1 300', 'tag @1 add defeated_sq_hz_analyst', '@2 say Refund issued, doubled, logged as a confidence event. The model did not see you coming. Neither did the model maker.', 'execute as @1 run function cobblemon_initiative:sidequest/minutes/billable_hours', 'execute as @1 run function cobblemon_initiative:economy/wager_sweetener'], 2: ['@1 say The stake stays with the house. Customer confidence: measurably improved. Thank you for participating in the figures.']}
