# decline_cinderfall_vexa — pay 570 CD to bow out of Vexa Ashclaw.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 570 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_cinderfall_vexa (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_cinderfall_vexa] unless entity @s[tag=defeated_cinderfall_vexa] store result score #decl_ok cd_calc run cobbledollars pay @s 570
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 570
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_cinderfall_vexa
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 570 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_cinderfall_vexa] unless entity @s[tag=defeated_cinderfall_vexa] run tbcs battle GEN_9_SINGLES @s vs rctmod:cinderfall_vexa onwin {1: ['cobbledollars give @1 1140', 'tag @1 add defeated_cinderfall_vexa', '@2 say You crossed the sulfur without choking. The terraces are yours - Scorchspire is below.', 'tag @1 remove in_trainer_battle'], 2: ['@1 say The fumes and the fire took you together. Clear your head and cross again.', 'tag @2 remove in_trainer_battle']}
