# decline_r8_typetip_dune — pay 300 CD to bow out of Sandreader Mafu.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 300 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_r8_typetip_dune (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_r8_typetip_dune] unless entity @s[tag=defeated_r8_typetip_dune] store result score #decl_ok cd_calc run cobbledollars pay @s 300
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 300
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_r8_typetip_dune
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 300 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_r8_typetip_dune] unless entity @s[tag=defeated_r8_typetip_dune] run tbcs battle GEN_9_SINGLES @s vs rctmod:r8_typetip_dune onwin {1: ['cobbledollars give @1 650', 'tag @1 add defeated_r8_typetip_dune', '@2 say Now you feel it. Earthquake finds every set of feet. Gaia will not surprise you.', 'tag @1 remove in_trainer_battle'], 2: ['@1 say The dune wins when you fight it standing still. Rest and read the sand again.', 'tag @2 remove in_trainer_battle']}
