# decline_cinderfall_drakar — pay 580 CD to bow out of Drakar Cinderstrike.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 580 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_cinderfall_drakar (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_cinderfall_drakar] unless entity @s[tag=defeated_cinderfall_drakar] store result score #decl_ok cd_calc run cobbledollars pay @s 580
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 580
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_cinderfall_drakar
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 580 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_cinderfall_drakar] unless entity @s[tag=defeated_cinderfall_drakar] run tbcs battle GEN_9_SINGLES @s vs rctmod:cinderfall_drakar onwin {1: ['cobbledollars give @1 1160', 'tag @1 add defeated_cinderfall_drakar', '@2 say You took the obsidian stair over my whole line. It is yours - one more, then Scorchspire.', 'tag @1 remove in_trainer_battle'], 2: ['@1 say The stair burned you off the glass. Regroup and descend again.', 'tag @2 remove in_trainer_battle']}
