# decline_nifl_warrant_officer — pay 140 CD to bow out of Warrant Officer Dain.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 140 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_nifl_warrant_officer (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_nifl_warrant_officer] unless entity @s[tag=defeated_nifl_warrant_officer] store result score #decl_ok cd_calc run cobbledollars pay @s 140
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 140
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_nifl_warrant_officer
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 140 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_nifl_warrant_officer] unless entity @s[tag=defeated_nifl_warrant_officer] run tbcs battle GEN_9_DOUBLES @s vs rctmod:nifl_warrant_officer onwin {1: ['cobbledollars give @1 480', 'tag @1 add defeated_nifl_warrant_officer', '@2 say Gate is yours. Twenty years and I lose it to a face I was ordered to forget. Fitting.', 'tag @1 add nifl_frostgate_clear', 'easy_npc delete @2'], 2: ['@1 say Hold the line, they said. I held it. It did not hold me.']}
