# decline_r13_sight_korin — pay 420 CD to bow out of Korin Flameclaw.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 420 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_r13_sight_korin (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_r13_sight_korin] unless entity @s[tag=defeated_r13_sight_korin] store result score #decl_ok cd_calc run cobbledollars pay @s 420
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 420
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_r13_sight_korin
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 420 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_r13_sight_korin] unless entity @s[tag=defeated_r13_sight_korin] run tbcs battle GEN_9_SINGLES @s vs rctmod:r13_sight_korin onwin {1: ['cobbledollars give @1 840', 'tag @1 add defeated_r13_sight_korin', '@2 say You cleared the wall. The Keep gate is yours - Ryujin is just one more dragon now.', 'tag @1 remove in_trainer_battle'], 2: ['@1 say The last pitch breaks the overconfident. Rest and take the wall again.', 'tag @2 remove in_trainer_battle']}
