# decline_r14_sight_torvald — pay 440 CD to bow out of Torvald Snowrunner.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 440 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_r14_sight_torvald (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_r14_sight_torvald] unless entity @s[tag=defeated_r14_sight_torvald] store result score #decl_ok cd_calc run cobbledollars pay @s 440
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 440
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_r14_sight_torvald
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 440 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_r14_sight_torvald] unless entity @s[tag=defeated_r14_sight_torvald] run tbcs battle GEN_9_SINGLES @s vs rctmod:r14_sight_torvald onwin {1: ['cobbledollars give @1 880', 'tag @1 add defeated_r14_sight_torvald', '@2 say Warm blood, cold field, clean win. The snowfield is yours - Nifl is past the drift.', 'tag @1 remove in_trainer_battle'], 2: ['@1 say The field froze you out. Warm up and cross again.', 'tag @2 remove in_trainer_battle']}
