# decline_sq_canvasser — pay 150 CD to bow out of Kazuo.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 150 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_sq_canvasser (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_sq_canvasser] unless entity @s[tag=defeated_sq_canvasser] store result score #decl_ok cd_calc run cobbledollars pay @s 150
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 150
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_sq_canvasser
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 150 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_sq_canvasser] unless entity @s[tag=defeated_sq_canvasser] run tbcs battle GEN_9_SINGLES @s vs rctmod:sq_canvasser onwin {1: ['cobbledollars give @1 280', 'tag @1 add defeated_sq_canvasser', '@2 say Noted. The route survey will describe you as a headwind.'], 2: ['@1 say Your objection has been processed and declined.']}
