# decline_sq_rui_wager — pay 100 CD to bow out of Netmender Bosun Rui.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 100 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_sq_rui_wager (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_sq_rui_wager] unless entity @s[tag=defeated_sq_rui_wager] store result score #decl_ok cd_calc run cobbledollars pay @s 100
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 100
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_sq_rui_wager
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 100 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_sq_rui_wager] unless entity @s[tag=defeated_sq_rui_wager] run tbcs battle GEN_9_SINGLES @s vs rctmod:sq_rui_wager onwin {1: ['cobbledollars give @1 200', 'tag @1 add defeated_sq_rui_wager', '@2 say Ha - you read the tide, not the wave. Two hundred, counted on the barrelhead. The fleet could use a hand like that.', 'execute as @1 run function cobblemon_initiative:economy/wager_sweetener'], 2: ['cobbledollars remove @2 200', '@1 say The sea keeps the stake, deckhand. It keeps everything eventually. No hard feelings and no refunds - I stopped giving those out the day the pay got restructured.']}
