# decline_sq_headcount_wager — pay 150 CD to bow out of Field Researcher Ume.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 150 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_sq_headcount_wager (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_sq_headcount_wager] unless entity @s[tag=defeated_sq_headcount_wager] store result score #decl_ok cd_calc run cobbledollars pay @s 150
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 150
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_sq_headcount_wager
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 150 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_sq_headcount_wager] unless entity @s[tag=defeated_sq_headcount_wager] run tbcs battle GEN_9_SINGLES @s vs rctmod:sq_headcount_wager onwin {1: ['cobbledollars give @1 900', 'tag @1 add defeated_sq_headcount_wager', '@2 say Documented. The purse is yours and the appendix is thicker for it.', 'execute as @1 run function cobblemon_initiative:economy/wager_sweetener'], 2: ['@1 say The stake goes to science. Payroll will find that hilarious.']}
