# decline_hakim_sefu — pay 300 CD to bow out of Hakim Sefu.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 300 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_hakim_sefu (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_hakim_sefu] unless entity @s[tag=defeated_hakim_sefu] store result score #decl_ok cd_calc run cobbledollars pay @s 300
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 300
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_hakim_sefu
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 300 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_hakim_sefu] unless entity @s[tag=defeated_hakim_sefu] run tbcs battle GEN_9_SINGLES @s vs rctmod:hakim_sefu onwin {1: ['cobbledollars give @1 640', 'tag @1 add defeated_hakim_sefu', '@2 say Strong. The dunes shift for you today. Kalahar is close now.', 'tag @1 remove in_trainer_battle'], 2: ['@1 say The sand takes the slow. Come back when your feet are surer.', 'tag @2 remove in_trainer_battle']}
