# decline_rashid_anwar — pay 300 CD to bow out of Rashid Anwar.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 300 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_rashid_anwar (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_rashid_anwar] unless entity @s[tag=defeated_rashid_anwar] store result score #decl_ok cd_calc run cobbledollars pay @s 300
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 300
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_rashid_anwar
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 300 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_rashid_anwar] unless entity @s[tag=defeated_rashid_anwar] run tbcs battle GEN_9_SINGLES @s vs rctmod:rashid_anwar onwin {1: ['cobbledollars give @1 620', 'tag @1 add defeated_rashid_anwar', '@2 say The road is yours to the next rise. Mind the crossing - the Company is thicker there.', 'tag @1 remove in_trainer_battle'], 2: ['@1 say The shoulder holds. Come back when your team can walk it.', 'tag @2 remove in_trainer_battle']}
