# decline_r3_trainer_selene — pay 180 CD to bow out of Selene.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 180 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_r3_trainer_selene (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_r3_trainer_selene] unless entity @s[tag=defeated_r3_trainer_selene] store result score #decl_ok cd_calc run cobbledollars pay @s 180
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 180
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_r3_trainer_selene
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 180 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_r3_trainer_selene] unless entity @s[tag=defeated_r3_trainer_selene] run tbcs battle GEN_9_SINGLES @s vs rctmod:r3_trainer_selene onwin {1: ['cobbledollars give @1 380', 'tag @1 add defeated_r3_trainer_selene', '@2 say A clean cross at the failing light. The marsh will remember you kindly.', 'tag @1 remove in_trainer_battle'], 2: ['@1 say The dusk never loses out here. Rest your team and try my hour again.', 'tag @2 remove in_trainer_battle']}
