# decline_cinderfall_ignar — pay 560 CD to bow out of Ignar Lavawalker.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 560 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_cinderfall_ignar (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_cinderfall_ignar] unless entity @s[tag=defeated_cinderfall_ignar] store result score #decl_ok cd_calc run cobbledollars pay @s 560
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 560
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_cinderfall_ignar
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 560 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_cinderfall_ignar] unless entity @s[tag=defeated_cinderfall_ignar] run tbcs battle GEN_9_SINGLES @s vs rctmod:cinderfall_ignar onwin {1: ['cobbledollars give @1 1120', 'tag @1 add defeated_cinderfall_ignar', '@2 say You walked the coals and did not burn. The upper ash road is yours - Scorchspire is below.', 'tag @1 remove in_trainer_battle'], 2: ['@1 say The lava took your footing. Cool off and walk the coals again.', 'tag @2 remove in_trainer_battle']}
