# decline_r7_trainer_serena — pay 250 CD to bow out of Serena Altacosta.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 250 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_r7_trainer_serena (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_r7_trainer_serena] unless entity @s[tag=defeated_r7_trainer_serena] store result score #decl_ok cd_calc run cobbledollars pay @s 250
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 250
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_r7_trainer_serena
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 250 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_r7_trainer_serena] unless entity @s[tag=defeated_r7_trainer_serena] run tbcs battle GEN_9_SINGLES @s vs rctmod:r7_trainer_serena onwin {1: ['cobbledollars give @1 540', 'tag @1 add defeated_r7_trainer_serena', '@2 say Clean footing on a bad wind. The coast road west is yours.', 'tag @1 remove in_trainer_battle'], 2: ['@1 say The tide takes the slow ones. Dry off and read the water again.', 'tag @2 remove in_trainer_battle']}
