# decline_cinderfall_karn — pay 600 CD to bow out of Karn Pyroclast.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 600 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_cinderfall_karn (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_cinderfall_karn] unless entity @s[tag=defeated_cinderfall_karn] store result score #decl_ok cd_calc run cobbledollars pay @s 600
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 600
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_cinderfall_karn
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 600 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_cinderfall_karn] unless entity @s[tag=defeated_cinderfall_karn] run tbcs battle GEN_9_SINGLES @s vs rctmod:cinderfall_karn onwin {1: ['cobbledollars give @1 1200', 'tag @1 add defeated_cinderfall_karn', '@2 say You burned through the last hammer. The caldera gate is open - Scorchspire and the tenth badge are below.', 'tag @1 remove in_trainer_battle'], 2: ['@1 say The last hammer of the Descent fell on you. Reforge and face the gate again.', 'tag @2 remove in_trainer_battle']}
