# decline_omar_tarek — pay 280 CD to bow out of Omar Tarek.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 280 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_omar_tarek (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_omar_tarek] unless entity @s[tag=defeated_omar_tarek] store result score #decl_ok cd_calc run cobbledollars pay @s 280
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 280
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_omar_tarek
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 280 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_omar_tarek] unless entity @s[tag=defeated_omar_tarek] run tbcs battle GEN_9_SINGLES @s vs rctmod:omar_tarek onwin {1: ['cobbledollars give @1 560', 'tag @1 add defeated_omar_tarek', '@2 say The tide takes its due, and today it took me. The dunes are yours.', 'tag @1 remove in_trainer_battle'], 2: ['@1 say Back to the wet with you. The desert keeps what the sea will not.', 'tag @2 remove in_trainer_battle']}
