# decline_nifl_records_officer — pay 120 CD to bow out of Records Officer Halden.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 120 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_nifl_records_officer (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_nifl_records_officer] unless entity @s[tag=defeated_nifl_records_officer] store result score #decl_ok cd_calc run cobbledollars pay @s 120
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 120
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_nifl_records_officer
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 120 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_nifl_records_officer] unless entity @s[tag=defeated_nifl_records_officer] run tbcs battle GEN_9_SINGLES @s vs rctmod:nifl_records_officer onwin {1: ['cobbledollars give @1 480', 'tag @1 add defeated_nifl_records_officer', '@2 say Retention will note the loss. Filed under - well. There is no line for what you are.', 'tag @1 add nifl_archive_open', 'easy_npc delete @2'], 2: ['@1 say The room is Company property. So is the face on the wall, and so, once, were you.']}
