# decline_sq_rt2_haoran — pay 130 CD to bow out of Deng Haoran.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 130 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_sq_rt2_haoran (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_sq_rt2_haoran] unless entity @s[tag=defeated_sq_rt2_haoran] store result score #decl_ok cd_calc run cobbledollars pay @s 130
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 130
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_sq_rt2_haoran
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 130 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_sq_rt2_haoran] unless entity @s[tag=defeated_sq_rt2_haoran] run tbcs battle GEN_9_SINGLES @s vs rctmod:sq_rt2_haoran onwin {1: ['cobbledollars give @1 260', 'tag @1 add defeated_sq_rt2_haoran', '@2 say You mean it more than I do. There is the purse — I will win it back off the next traveler, watch me.', 'tag @1 remove in_trainer_battle'], 2: ['@1 say Phanpy eats first tonight. House rule — winner picks the bowl order.', 'tag @2 remove in_trainer_battle']}
