# decline_r7_spotter_coast — pay 260 CD to bow out of Gull-Keeper Hano.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 260 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_r7_spotter_coast (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_r7_spotter_coast] unless entity @s[tag=defeated_r7_spotter_coast] store result score #decl_ok cd_calc run cobbledollars pay @s 260
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 260
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_r7_spotter_coast
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 260 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_r7_spotter_coast] unless entity @s[tag=defeated_r7_spotter_coast] run tbcs battle GEN_9_SINGLES @s vs rctmod:r7_spotter_coast onwin {1: ['cobbledollars give @1 560', 'tag @1 add defeated_r7_spotter_coast', '@2 say Clean footing on a bad wind. The coast road is yours.', 'tag @1 remove in_trainer_battle'], 2: ['@1 say The tide takes the slow ones. Dry off and read the wind again.', 'tag @2 remove in_trainer_battle']}
