# decline_r16_sight_ronan — pay 490 CD to bow out of Ronan Peakguard.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 490 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_r16_sight_ronan (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_r16_sight_ronan] unless entity @s[tag=defeated_r16_sight_ronan] store result score #decl_ok cd_calc run cobbledollars pay @s 490
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 490
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_r16_sight_ronan
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 490 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_r16_sight_ronan] unless entity @s[tag=defeated_r16_sight_ronan] run tbcs battle GEN_9_SINGLES @s vs rctmod:r16_sight_ronan onwin {1: ['cobbledollars give @1 980', 'tag @1 add defeated_r16_sight_ronan', '@2 say Strong opener. The canyon mouth is yours - the Road only gets meaner from here.', 'tag @1 remove in_trainer_battle'], 2: ['@1 say Even the easy start of the Road found your gaps. Regroup and take the canyon again.', 'tag @2 remove in_trainer_battle']}
