# decline_r16_sight_lysandra — pay 540 CD to bow out of Lysandra Skyflare.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 540 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_r16_sight_lysandra (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_r16_sight_lysandra] unless entity @s[tag=defeated_r16_sight_lysandra] store result score #decl_ok cd_calc run cobbledollars pay @s 540
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 540
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_r16_sight_lysandra
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 540 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_r16_sight_lysandra] unless entity @s[tag=defeated_r16_sight_lysandra] run tbcs battle GEN_9_SINGLES @s vs rctmod:r16_sight_lysandra onwin {1: ['cobbledollars give @1 1080', 'tag @1 add defeated_r16_sight_lysandra', '@2 say You beat the last wall of the Road. Through the arch is Scorchspire and the tenth badge. Go take it.', 'tag @1 remove in_trainer_battle'], 2: ['@1 say The last wall of the Road held. Whatever broke, mend it, and face the arch again.', 'tag @2 remove in_trainer_battle']}
