# decline_r10_spotter_caravan — pay 240 CD to bow out of Caravan Guard Boro.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 240 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_r10_spotter_caravan (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_r10_spotter_caravan] unless entity @s[tag=defeated_r10_spotter_caravan] store result score #decl_ok cd_calc run cobbledollars pay @s 240
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 240
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_r10_spotter_caravan
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 240 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_r10_spotter_caravan] unless entity @s[tag=defeated_r10_spotter_caravan] run tbcs battle GEN_9_SINGLES @s vs rctmod:r10_spotter_caravan onwin {1: ['cobbledollars give @1 520', 'tag @1 add defeated_r10_spotter_caravan', '@2 say Cleared. The road is yours - a guard only checks a face once.', 'tag @1 remove in_trainer_battle'], 2: ['@1 say The artery keeps its own. Rest at the crossing and try the road again.', 'tag @2 remove in_trainer_battle']}
