# decline_sq_regular_4 — pay 110 CD to bow out of Zola.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 110 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_sq_regular_4 (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_sq_regular_4] unless entity @s[tag=defeated_sq_regular_4] store result score #decl_ok cd_calc run cobbledollars pay @s 110
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 110
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_sq_regular_4
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 110 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_sq_regular_4] unless entity @s[tag=defeated_sq_regular_4] run tbcs battle GEN_9_SINGLES @s vs rctmod:sq_regular_4 onwin {1: ['cobbledollars give @1 220', 'tag @1 add defeated_sq_regular_4', '@2 say Fair and square. The dandelions saw the whole thing - they will tell the wind, and the wind tells everyone.', 'tag @1 remove in_trainer_battle'], 2: ['@1 say The meadow keeps its own. Sit a moment, catch your breath, and we go again whenever.', 'tag @2 remove in_trainer_battle']}
