# decline_sq_deepcore_assessor — pay 120 CD to bow out of Roderick.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 120 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_sq_deepcore_assessor (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_sq_deepcore_assessor] unless entity @s[tag=defeated_sq_deepcore_assessor] store result score #decl_ok cd_calc run cobbledollars pay @s 120
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 120
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_sq_deepcore_assessor
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 120 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_sq_deepcore_assessor] unless entity @s[tag=defeated_sq_deepcore_assessor] run tbcs battle GEN_9_SINGLES @s vs rctmod:sq_deepcore_assessor onwin {1: ['cobbledollars give @1 500', 'tag @1 add defeated_sq_deepcore_assessor', '@2 say Adjustment reversed. The vault is yours to read. I was told you were a closed file - the file appears to be open.'], 2: ['@1 say Non-compliance is billable. The stake reconciles in the Company favor. Do enjoy the receipt.']}
