# decline_sq_regular_meadow — pay 80 CD to bow out of Jabari.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 80 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_sq_regular_meadow (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_sq_regular_meadow] unless entity @s[tag=defeated_sq_regular_meadow] store result score #decl_ok cd_calc run cobbledollars pay @s 80
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 80
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_sq_regular_meadow
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 80 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_sq_regular_meadow] unless entity @s[tag=defeated_sq_regular_meadow] run tbcs battle GEN_9_SINGLES @s vs rctmod:sq_regular_meadow onwin {1: ['cobbledollars give @1 150', 'tag @1 add defeated_sq_regular_meadow', '@2 say Oh, they liked that. They always fight better for an audience.'], 2: ['@1 say The meadow looks after its own. No hard feelings - have a snack before you go.']}
