# decline_sq_recovery_agent — pay 250 CD to bow out of Recovery Agent Kessler.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 250 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_sq_recovery_agent (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_sq_recovery_agent] unless entity @s[tag=defeated_sq_recovery_agent] store result score #decl_ok cd_calc run cobbledollars pay @s 250
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 250
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_sq_recovery_agent
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 250 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_sq_recovery_agent] unless entity @s[tag=defeated_sq_recovery_agent] run tbcs battle GEN_9_SINGLES @s vs rctmod:sq_recovery_agent onwin {1: ['cobbledollars give @1 600', 'tag @1 add defeated_sq_recovery_agent', '@2 say Shipment lost. Note for the file - the subject sets their feet like someone who used to sign these. I am reassigning myself before I have to write that down.', 'tag @1 add forge_order_agent_clear', 'easy_npc delete @2'], 2: ['@1 say Order collected. The Company records this cooperation and thanks the forge.']}
