# decline_r15_trainer_ember — pay 450 CD to bow out of Emberwalker Tavi.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 450 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_r15_trainer_ember (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_r15_trainer_ember] unless entity @s[tag=defeated_r15_trainer_ember] store result score #decl_ok cd_calc run cobbledollars pay @s 450
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 450
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_r15_trainer_ember
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 450 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_r15_trainer_ember] unless entity @s[tag=defeated_r15_trainer_ember] run tbcs battle GEN_9_SINGLES @s vs rctmod:r15_trainer_ember onwin {1: ['cobbledollars give @1 1000', 'tag @1 add defeated_r15_trainer_ember', '@2 say Real fire, and you did not flinch. Scorchspire will not surprise you now.'], 2: ['@1 say The mountain teaches with heat. Cool off and climb back up when you are ready.']}
