# decline_nadir_khemet — pay 300 CD to bow out of Nadir Khemet.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 300 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_nadir_khemet (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_nadir_khemet] unless entity @s[tag=defeated_nadir_khemet] store result score #decl_ok cd_calc run cobbledollars pay @s 300
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 300
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_nadir_khemet
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 300 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_nadir_khemet] unless entity @s[tag=defeated_nadir_khemet] run tbcs battle GEN_9_SINGLES @s vs rctmod:nadir_khemet onwin {1: ['cobbledollars give @1 620', 'tag @1 add defeated_nadir_khemet', '@2 say Proven. Keep your footing past the bend and the leg is easy.', 'tag @1 remove in_trainer_battle'], 2: ['@1 say The scree keeps you. Mend up and try the bend again.', 'tag @2 remove in_trainer_battle']}
