# decline_r14_spotter_frost — pay 380 CD to bow out of Frostwarden Neve.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 380 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_r14_spotter_frost (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_r14_spotter_frost] unless entity @s[tag=defeated_r14_spotter_frost] store result score #decl_ok cd_calc run cobbledollars pay @s 380
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 380
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_r14_spotter_frost
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 380 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_r14_spotter_frost] unless entity @s[tag=defeated_r14_spotter_frost] run tbcs battle GEN_9_SINGLES @s vs rctmod:r14_spotter_frost onwin {1: ['cobbledollars give @1 850', 'tag @1 add defeated_r14_spotter_frost', '@2 say Warm blood, cold nerve. You take the ice better than most. Nifl is yours to reach.', 'tag @1 remove in_trainer_battle'], 2: ['@1 say The pass takes the unprepared. Thaw out at the waypost and try the crossing again.', 'tag @2 remove in_trainer_battle']}
