# decline_r13_sight_lyra — pay 400 CD to bow out of Lyra Stormflight.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 400 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_r13_sight_lyra (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_r13_sight_lyra] unless entity @s[tag=defeated_r13_sight_lyra] store result score #decl_ok cd_calc run cobbledollars pay @s 400
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 400
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_r13_sight_lyra
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 400 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_r13_sight_lyra] unless entity @s[tag=defeated_r13_sight_lyra] run tbcs battle GEN_9_SINGLES @s vs rctmod:r13_sight_lyra onwin {1: ['cobbledollars give @1 800', 'tag @1 add defeated_r13_sight_lyra', '@2 say You ride the crosswind true. The windward shelf is yours - the Keep is one storm higher.', 'tag @1 remove in_trainer_battle'], 2: ['@1 say The wind took you off the shelf. Find your footing and ride again.', 'tag @2 remove in_trainer_battle']}
