# decline_sq_marigold_charm — pay 100 CD to bow out of Charm-Weaver Marigold.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 100 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_sq_marigold_charm (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_sq_marigold_charm] unless entity @s[tag=defeated_sq_marigold_charm] store result score #decl_ok cd_calc run cobbledollars pay @s 100
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 100
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_sq_marigold_charm
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 100 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_sq_marigold_charm] unless entity @s[tag=defeated_sq_marigold_charm] run tbcs battle GEN_9_SINGLES @s vs rctmod:sq_marigold_charm onwin {1: ['cobbledollars give @1 200', 'tag @1 add defeated_sq_marigold_charm', '@2 say Ha - the cards said you would win and I still bet against them. The marsh keeps me humble. Two hundred, and a reading thrown in for free.'], 2: ['cobbledollars remove @2 200', '@1 say The stake stays with the weaver, as the old rule goes. No hard feelings - luck is a loan, and today the fen called it in.']}
