# decline_r16_sight_drake — pay 520 CD to bow out of Drake Ironclaw.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 520 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_r16_sight_drake (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_r16_sight_drake] unless entity @s[tag=defeated_r16_sight_drake] store result score #decl_ok cd_calc run cobbledollars pay @s 520
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 520
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_r16_sight_drake
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 520 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_r16_sight_drake] unless entity @s[tag=defeated_r16_sight_drake] run tbcs battle GEN_9_SINGLES @s vs rctmod:r16_sight_drake onwin {1: ['cobbledollars give @1 1040', 'tag @1 add defeated_r16_sight_drake', '@2 say A real climb over you and you carried it. The high shelf is yours - one more, then the summit.', 'tag @1 remove in_trainer_battle'], 2: ['@1 say The high shelf is where good teams end. Regroup and take the wall again.', 'tag @2 remove in_trainer_battle']}
