# decline_sq_rt2_scarecrow — pay 120 CD to bow out of Scarecrow Wrangler Mirek.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 120 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_sq_rt2_scarecrow (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_sq_rt2_scarecrow] unless entity @s[tag=defeated_sq_rt2_scarecrow] store result score #decl_ok cd_calc run cobbledollars pay @s 120
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 120
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_sq_rt2_scarecrow
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 120 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_sq_rt2_scarecrow] unless entity @s[tag=defeated_sq_rt2_scarecrow] run tbcs battle GEN_9_SINGLES @s vs rctmod:sq_rt2_scarecrow onwin {1: ['cobbledollars give @1 230', 'tag @1 add defeated_sq_rt2_scarecrow', '@2 say Sharp work. The crows would scatter for you without a single scarecrow.', 'tag @1 remove in_trainer_battle'], 2: ['@1 say Ha — the birds still earn better than the vouchers do. Rest yours and come back.', 'tag @2 remove in_trainer_battle']}
