# decline_r3_trainer_rowan — pay 200 CD to bow out of Rowan.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 200 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_r3_trainer_rowan (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_r3_trainer_rowan] unless entity @s[tag=defeated_r3_trainer_rowan] store result score #decl_ok cd_calc run cobbledollars pay @s 200
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 200
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_r3_trainer_rowan
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 200 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_r3_trainer_rowan] unless entity @s[tag=defeated_r3_trainer_rowan] run tbcs battle GEN_9_SINGLES @s vs rctmod:r3_trainer_rowan onwin {1: ['cobbledollars give @1 420', 'tag @1 add defeated_r3_trainer_rowan', '@2 say There it is. You move like the venom now. The mist court is going to hate you.', 'tag @1 remove in_trainer_battle'], 2: ['@1 say Stung and schooled. Rest up, come back, and this time answer venom with venom.', 'tag @2 remove in_trainer_battle']}
