# decline_r16_spotter_causeway — pay 500 CD to bow out of Frontier Scout Rhea.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 500 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_r16_spotter_causeway (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_r16_spotter_causeway] unless entity @s[tag=defeated_r16_spotter_causeway] store result score #decl_ok cd_calc run cobbledollars pay @s 500
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 500
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_r16_spotter_causeway
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 500 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_r16_spotter_causeway] unless entity @s[tag=defeated_r16_spotter_causeway] run tbcs battle GEN_9_SINGLES @s vs rctmod:r16_spotter_causeway onwin {1: ['cobbledollars give @1 1100', 'tag @1 add defeated_r16_spotter_causeway', '@2 say Clean crossing. You have earned the far arch - the League will not intimidate you.', 'tag @1 remove in_trainer_battle'], 2: ['@1 say The causeway does not forgive a slow team on the open run. Regroup and cross again.', 'tag @2 remove in_trainer_battle']}
