# decline_r5_trainer_quarry — pay 240 CD to bow out of Rockbreaker Dala.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 240 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_r5_trainer_quarry (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_r5_trainer_quarry] unless entity @s[tag=defeated_r5_trainer_quarry] store result score #decl_ok cd_calc run cobbledollars pay @s 240
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 240
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_r5_trainer_quarry
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 240 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_r5_trainer_quarry] unless entity @s[tag=defeated_r5_trainer_quarry] run tbcs battle GEN_9_SINGLES @s vs rctmod:r5_trainer_quarry onwin {1: ['cobbledollars give @1 520', 'tag @1 add defeated_r5_trainer_quarry', '@2 say Solid. You hit like the quarry hits back. Deepcore will like you.', 'tag @1 remove in_trainer_battle'], 2: ['@1 say Stone teaches patience. Come swing again.', 'tag @2 remove in_trainer_battle']}
