# decline_sq_regular_typetip — pay 130 CD to bow out of Bird Keeper Kwame.
# AUTO-GENERATED by scripts/content_compile from battle.decline_fee — edit the
# character JSON, not this file. Runs AS the player (bare as_player function call
# from the bow-out dialog button). CobbleDollars `pay` soft-fails when broke, so
# gate on `store result` (0 = broke, 130 = paid) — the heal_paid probe pattern.
# Paid -> receipt + permanent declined_sq_regular_typetip (stand-down: hail/touch/battle all
# gate on it). Broke -> the battle fires (must-fight; same line as the button).
scoreboard players set #decl_ok cd_calc 0
execute unless entity @s[tag=declined_sq_regular_typetip] unless entity @s[tag=defeated_sq_regular_typetip] store result score #decl_ok cd_calc run cobbledollars pay @s 130
execute if score #decl_ok cd_calc matches 1.. run cobbledollars remove @s 130
execute if score #decl_ok cd_calc matches 1.. run tag @s add declined_sq_regular_typetip
execute if score #decl_ok cd_calc matches 1.. run title @s actionbar [{"text":"Verified Charge: 130 CD. ","color":"gold"},{"text":"Non-engagement processed. No further challenge is scheduled.","color":"gray"}]
execute if score #decl_ok cd_calc matches 0 unless entity @s[tag=declined_sq_regular_typetip] unless entity @s[tag=defeated_sq_regular_typetip] run tbcs battle GEN_9_SINGLES @s vs rctmod:sq_regular_typetip onwin {1: ['cobbledollars give @1 250', 'tag @1 add defeated_sq_regular_typetip', '@2 say There it is. Now you know why the bugs hide when the flock passes. Take this potion - you will want it at the falls.', 'tag @1 remove in_trainer_battle'], 2: ['@1 say The sky does not lose to the meadow often. Rest up and try again.', 'tag @2 remove in_trainer_battle']}
